<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
        <IsPublishable>false</IsPublishable>
    <IsTrimmable>false</IsTrimmable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/LibExecution/LibExecution.fsproj" />
    <ProjectReference Include="../../src/LibParser/LibParser.fsproj" />
    <ProjectReference Include="../../src/LibDB/LibDB.fsproj" />
    <ProjectReference Include="../../src/Platforms/Platforms.fsproj" />
    <ProjectReference Include="../../src/LibCloud/LibCloud.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="PackageSurface.fs" />
    <Compile Include="PTShortcuts.fs" />
    <Compile Include="LibTest.fs" />
    <Compile Include="TestUtils.fs" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
