/// Writes `package-ref-hashes.txt` with current hashes from the DB.
/// PackageRefs.fs reads this file at startup.
module LibDB.PackageManager.PackageRefsGenerator

open Prelude

open Fumble
open LibSqlite.Db

module PackageRefs = LibExecution.PackageRefs


/// Build the FQN key for a given item type and DB row.
/// Format: "type/{modules}.{name}" or "fn/{modules}.{name}"
let private buildKey (itemType : string) (modules : string) (name : string) =
  let prefix = if itemType = "type" then "type" else "fn"
  if modules = "" then $"{prefix}/{name}" else $"{prefix}/{modules}.{name}"


/// Path to the source-tree copy of the hash file (NOT committed to git;
/// gitignored, regenerated by every reload-packages run).
///
/// Path is relative to this source file's location:
/// `backend/src/LibDB/PackageManager/PackageRefsGenerator.fs` →
/// `backend/src/LibExecution/package-ref-hashes.txt`. That's two `..`
/// hops, not one.
let private sourceTreePath =
  System.IO.Path.Combine(
    __SOURCE_DIRECTORY__,
    "../../LibExecution/package-ref-hashes.txt"
  )
  |> System.IO.Path.GetFullPath


/// Query the DB for all current Darklang-owned locations and write
/// `package-ref-hashes.txt` in the source tree.
///
/// We write ALL Darklang-owned items, not just the ones in `PackageRefs._lookup`.
/// The `_lookup` maps are populated lazily via F# module init when something in
/// `LibExecution.PackageRefs.Type.<sub>` or `Fn.<sub>` is referenced — but
/// `LocalExec.reload-packages` doesn't necessarily traverse those code paths
/// before calling `generate`, so `_lookup` could be empty here. Writing the
/// full set is a small file-size hit (~3500 entries vs ~150) and fixes the
/// bootstrap for any caller of `LibExecution.PackageRefs` later.
let generate () : Ply<unit> =
  uply {
    // Query all Darklang-owned locations from DB
    let! dbRows =
      Sql.query
        """
        SELECT item_type, modules, name, item_hash
        FROM locations
        WHERE owner = 'Darklang'
          AND unlisted_at IS NULL
        """
      |> Sql.executeAsync (fun read ->
        let itemType = read.string "item_type"
        let modules = read.string "modules"
        let name = read.string "name"
        let hash = read.string "item_hash"
        (buildKey itemType modules name, hash))

    // Dedupe (multiple locations can point at the same hash; PK is item_hash)
    let merged = dbRows |> Map.ofList |> Map.toList |> List.sortBy fst

    let lines = merged |> List.map (fun (key, hash) -> $"{key}|{hash}")

    // Always set the in-memory cache so PackageRefs lookups work without a
    // restart-and-reload cycle.
    let hashMap = merged |> Map.ofList
    PackageRefs.setHashes hashMap

    // Write the source-tree file (skip if the directory doesn't exist,
    // e.g. on installed CLIs where the source tree isn't available)
    let dir = System.IO.Path.GetDirectoryName(sourceTreePath)
    if System.IO.Directory.Exists(dir) then
      System.IO.File.WriteAllLines(sourceTreePath, lines |> Array.ofList)
      let totalWritten = List.length lines
      print $"  Wrote {totalWritten} package ref hashes to {sourceTreePath}"
  }
