apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-tunnel
spec:
  podSelector:
    matchLabels:
      app:
        tunnel-app
  policyTypes:
    - Egress
    - Ingress
  egress:
    - to:
        - ipBlock:
            # Allows all IPs
            cidr: 0.0.0.0/0
            except:
              # make sure to block link-local addresses,
              # since there's sensitive data in http://metadata
              - 169.254.0.0/16

  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values: [bwd-app, qw-worker, cron-checker, editor-app]
