apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel-deployment
  annotations:
    kubernetes.io/change-cause: "{CHANGE_CAUSE}"
spec:
  selector:
    matchLabels:
      app: tunnel-app
  revisionHistoryLimit: 10
  replicas: 1
  template:
    metadata:
      labels:
        app: tunnel-app
    spec:
      containers:
        - name: tunnel-ctr
          image: gcr.io/balmy-ground-195100/tunnel:{TUNNEL_IMAGE}
          # Resource limits + requests are intentionally the same, to ensure
          # this pod is a 'Guaranteed' pod, ref:
          #  https://medium.com/google-cloud/quality-of-service-class-qos-in-kubernetes-bb76a89eb2c6
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - name: tunnel-port
              containerPort: 1080
          livenessProbe:
            exec:
              command:
                ["curl", "--max-time", "5", "-x", "socks5h://localhost:1080", "example.com"]
            initialDelaySeconds: 1
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                ["curl", "--max-time", "5", "-x", "socks5h://localhost:1080", "example.com"]
            initialDelaySeconds: 1
            periodSeconds: 5
