kind: Service
apiVersion: v1
metadata:
  name: tunnel-service
spec:
  type: ClusterIP
  selector:
    app: tunnel-app
  ports:
    - name: tunnel-clusterip-port
      protocol: TCP
      port: 1080
      targetPort: tunnel-port
