open Core_kernel
open Lib
open Types.RuntimeT
module RT = Runtime

let fns : Lib.shortfn list =
  [ { pns = ["StaticAssets::baseUrlFor"]
    ; ins = []
    ; p = [par "deploy_hash" TStr]
    ; r = TStr
    ; d = "Return the baseUrl for the specified deploy hash"
    ; f = NotClientAvailable
    ; ps = false
    ; dep = false }
  ; { pns = ["StaticAssets::baseUrlForLatest"]
    ; ins = []
    ; p = []
    ; r = TStr
    ; d = "Return the baseUrl for the latest deploy"
    ; f = NotClientAvailable
    ; ps = false
    ; dep = false }
  ; { pns = ["StaticAssets::urlFor"]
    ; ins = []
    ; p = [par "deploy_hash" TStr; par "file" TStr]
    ; r = TStr
    ; d = "Return a url for the specified file and deploy hash"
    ; f = NotClientAvailable
    ; ps = false
    ; dep = false }
  ; { pns = ["StaticAssets::urlForLatest"]
    ; ins = []
    ; p = [par "file" TStr]
    ; r = TStr
    ; d = "Return a url for the specified file and latest deploy"
    ; f = NotClientAvailable
    ; ps = false
    ; dep = false }
  ; { pns = ["StaticAssets::fetch"]
    ; ins = []
    ; p = [par "deploy_hash" TStr; par "file" TStr]
    ; r = TResult
    ; d =
        "Return the specified file from the deploy_hash - only works on UTF8-safe files for now"
    ; f = NotClientAvailable
    ; ps = false
    ; dep = false }
  ; { pns = ["StaticAssets::fetchBytes"]
    ; ins = []
    ; p = [par "deploy_hash" TStr; par "file" TStr]
    ; r = TResult
    ; d = "Return the bytes of the specified file from the deploy_hash"
    ; f = NotClientAvailable
    ; ps = false
    ; dep = false }
  ; { pns = ["StaticAssets::fetchLatest"]
    ; ins = []
    ; p = [par "file" TStr]
    ; r = TResult
    ; d =
        "Return the specified file from the latest deploy - only works on UTF8-safe files for now"
    ; f = NotClientAvailable
    ; ps = false
    ; dep = false }
  ; { pns = ["StaticAssets::fetchLatestBytes"]
    ; ins = []
    ; p = [par "file" TStr]
    ; r = TResult
    ; d = "Return the bytes of the specified file from the latest deploy"
    ; f = NotClientAvailable
    ; ps = false
    ; dep = false }
  ; { pns = ["StaticAssets::serve"]
    ; ins = []
    ; p = [par "deploy_hash" TStr; par "file" TStr]
    ; r = TResult
    ; d =
        "Return the specified file from the latest deploy - only works on UTF8-safe files for now"
    ; f = NotClientAvailable
    ; ps = false
    ; dep = true }
  ; { pns = ["StaticAssets::serve_v1"]
    ; ins = []
    ; p = [par "deploy_hash" TStr; par "file" TStr]
    ; r = TResult
    ; d = "Return the specified file from the latest deploy"
    ; f = NotClientAvailable
    ; ps = false
    ; dep = false }
  ; { pns = ["StaticAssets::serveLatest"]
    ; ins = []
    ; p = [par "file" TStr]
    ; r = TResult
    ; d =
        "Return the specified file from the latest deploy - only works on UTF8-safe files for now"
    ; f = NotClientAvailable
    ; ps = false
    ; dep = true }
  ; { pns = ["StaticAssets::serveLatest_v1"]
    ; ins = []
    ; p = [par "file" TStr]
    ; r = TResult
    ; d = "Return the specified file from the latest deploy"
    ; f = NotClientAvailable
    ; ps = false
    ; dep = false } ]
