#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"
set -eou pipefail

HELP="$(cat <<EOF
Usage: $0 DOMAIN CANVASNAME

Add a custom domain to the DB, resolving DOMAIN to CANVASNAME.

(This is a low-level script, you should probably use scripts/custom-domains/add)

For more docs, see docs/custom-domains.md.
EOF
)"

if [[ $# -ne 2 || "$1" == '--help' ]]; then
    echo "$HELP"
    exit 1
fi

DOMAIN=$1
CANVAS=$2

echo "Adding (host,canvas)=(${DOMAIN},${CANVAS}) to custom_domains to configure routing..."
# This tmpfile crap is because for some reason gcp-psql hangs when put into a
# subshell ( foo=$(... | ./scripts/production/gcp-psql) ) or when its output is piped to
# another command (... | ./scripts/production/gcp-psql | grep ...)
tmpfile=$(mktemp /tmp/custom_domain.XXXXXX)
insert_query="INSERT INTO custom_domains (host, canvas) VALUES ('${DOMAIN}', '${CANVAS}')"
echo "\\copy (${insert_query} returning (host, canvas)) TO ${tmpfile}" \
    | ./scripts/production/gcp-psql
if ( grep . < "${tmpfile}" > /dev/null ); then
    echo "Added (${DOMAIN}, ${CANVAS}) to custom_domains table."
else
    echo "Failed to add (${DOMAIN}, ${CANVAS}) to custom_domains table - possibly there's already an entry for ${DOMAIN}, or you lack db creds?"
    exit 1
fi
