#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"
set -eou pipefail

HELP="$(cat <<EOF
Usage: $0 DOMAIN

Check if the the cert for domain has been added

(This is a low-level script, you should probably use scripts/custom-domains/add)

For more docs, see docs/custom-domains.md.
EOF
)"

if [[ $# -ne 1 || "$1" == '--help' ]]; then
    echo "$HELP"
    exit 1
fi

DOMAIN=$1

echo "Waiting for cert to become ready - we'll wait up to 60s, if this goes
beyond that, something is probably wrong, check events in kubernetes for the
certificate resource".
# shellcheck disable=SC2034
for i in {1..12}; do
    cert_ready=$(kubectl get certs | awk "\$1 == \"${DOMAIN}-tls\" { print \$2 }")
    if [[ "$cert_ready" == "True" ]]; then
        break;
    else
        echo -n .
        sleep 5s
    fi
done

if [[ "$cert_ready" == "True" ]]; then
    echo # In case our previous output above was 'echo -n .' with no newline
    echo "Cert is ready!"
else
    echo "Cert is still not ready. You should check the events at"
    echo "kubectl describe certificate ${DOMAIN}-tls"
    echo "or possibly on the ingress"
    echo "kubectl describe ingress -n darklang darkcustomdomain-tls-ingress"
fi
