#!/usr/bin/env bash

. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -eou pipefail

PATH=~/.local/bin:$PATH

HELP="$(cat <<EOF
Usage: $0 DOMAIN

Removes DOMAIN from the custom_domains table. It does not remove the SSL cert.

For more docs, see docs/custom-domains.md
EOF
)"

if [[ $# -ne 1 || "$1" == '--help' ]]; then
    echo "$HELP"
    exit 1
fi

DOMAIN=$1

# This tmpfile crap is because for some reason gcp-psql hangs when put into a
# subshell ( foo=$(... | ./scripts/production/gcp-psql) ) or when its output is piped to
# another command (... | ./scripts/production/gcp-psql | grep ...)
tmpfile=$(mktemp /tmp/custom_domain.XXXXXX)
delete_query="DELETE FROM custom_domains WHERE host = '${DOMAIN}'"
echo "\\copy (${delete_query} RETURNING (host, canvas)) TO ${tmpfile}" \
    | ./scripts/production/gcp-psql
if ( grep . < "${tmpfile}" > /dev/null ); then
    echo "Deleted ${DOMAIN} from custom_domains table."
else
    echo "Failed to remove ${DOMAIN} from custom_domains table - possibly it wasn't there, or you lack db creds?"
    exit 1
fi
