#!/usr/bin/env bash

. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -eou pipefail

HELP="$(cat <<EOF
Usage: $0 DOMAIN

Looks up DOMAIN in the DNS and prints the canvas it points to

(This is a low-level script, you should probably use scripts/custom-domains/add)

For more docs, see docs/custom-domains.md.
EOF
)"

if [[ $# -ne 1 || "$1" == '--help' ]]; then
    echo >&2 "$HELP"
    exit 1
fi

DOMAIN=$1

dig_cname="$(dig "$DOMAIN" +short CNAME | head -n 1 | sed 's/.$//')"

if [[ "${dig_cname}" =~ \.darkcustomdomain\.com$ || "${dig_cname}" =~ \.builtwithdark\.com$ ]]; then
  true
elif [[ "${dig_cname}" == "" ]]; then
  echo >&2 "No CNAME found for ${DOMAIN}"
  exit 1
else
  echo >&2 "Expected a <something>.darkcustomdomain.com CNAME, but got ${dig_cname}, can't continue until this is fixed."
  exit 1
fi

CANVAS=${dig_cname//\.darkcustomdomain.com/}
CANVAS=${CANVAS//\.builtwithdark.com/}
echo "${CANVAS}"
