#!/usr/bin/env bash
set -euo pipefail
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

NAME=$1
DATE=$(date -u +%Y%m%d_%H%M%S)

FILE=backend/migrations/${DATE}_${NAME}.sql
touch "${FILE}"
git add "${FILE}"
