#!/usr/bin/env bash

set -euo pipefail

mkdir -p "$DARK_CONFIG_RUNDIR"

./scripts/devcontainer/_write-config-file
./scripts/devcontainer/_create-app-directories

echo "Starting apiserver"
./app/ApiServer
