#!/bin/bash

# Script to install yugabyte

set -e;

for i in "$@" ; do
  case "${i}" in
    --version=*)
    YUGABYTE_VERSION=${1/--version=/''}
    shift
    ;;
    --build=*)
    YUGABYTE_BUILD=${1/--build=/''}
    shift
    ;;  esac
done

case ${TARGETARCH} in
  arm64)
  URL=https://downloads.yugabyte.com/releases/$YUGABYTE_VERSION/yugabyte-$YUGABYTE_VERSION-$YUGABYTE_BUILD-el8-aarch64.tar.gz
  ;;
  amd64)
  URL=https://downloads.yugabyte.com/releases/$YUGABYTE_VERSION/yugabyte-$YUGABYTE_VERSION-$YUGABYTE_BUILD-linux-x86_64.tar.gz
  ;;
  *) exit 1 ;;
esac
FILENAME=$(basename $URL)
DIR=/home/dark/yugabyte
mkdir -p $DIR
cd $DIR
curl -sSL -o $FILENAME $URL
tar xvf $FILENAME --strip-components=1
rm $FILENAME
./bin/post_install.sh
case $(dpkg --print-architecture) in
  arm64)
  sudo ln -sf /usr/lib/aarch64-linux-gnu/liblber-2.5.so.0 /usr/lib/aarch64-linux-gnu/liblber-2.4.so.2
  sudo ln -sf /usr/lib/aarch64-linux-gnu/libldap-2.5.so.0 /usr/lib/aarch64-linux-gnu/libldap_r-2.4.so.2
  ;;
  amd64)
  sudo ln -sf /usr/lib/x86_64-linux-gnu/liblber-2.5.so.0 /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2
  sudo ln -sf /usr/lib/x86_64-linux-gnu/libldap-2.5.so.0 /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2
  ;;
  *) exit 1;;
esac
# python on our system is called python3
sed -i 's|#!/usr/bin/env python|#!/usr/bin/env python3|' ./bin/yugabyted
cd ..
