#!/bin/bash

# Script to install dotnet 8

set -e
case ${TARGETARCH} in
  arm64)
    ARCH=arm64
    CHECKSUM=$DOTNET_SDK_ARM64_CHECKSUM
    ;;
  amd64)
    ARCH=x64
    CHECKSUM=$DOTNET_SDK_X64_CHECKSUM
    ;;
  *) exit 1;;
esac
curl -SL --output dotnet.tar.gz https://dotnetcli.azureedge.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-${ARCH}.tar.gz
echo "$CHECKSUM dotnet.tar.gz" | sha512sum -c -
sudo mkdir -p /usr/share/dotnet
sudo tar -C /usr/share/dotnet -oxzf dotnet.tar.gz .
sudo rm dotnet.tar.gz
# Trigger first run experience by running arbitrary cmd
sudo ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
dotnet --help
