(* module Encoders = struct *)
(*   let entryCursor ec = *)
(*     let open Types_copy in *)
(*     match ec with *)
(*     | Creating p -> *)
(*       E.encodeVariant "Creating" [pos p] *)
(*     | Filling (tlid_, id_) -> *)
(*       E.encodeVariant "Filling" [tlid tlid_; id id_] *)
(*   let rec cursorState cs = *)
(*     let open Types_copy in *)
(*     match cs with *)
(*     | Selecting (tlid_, id_) -> *)
(*       E.encodeVariant "Selecting" [tlid tlid_; E.nullable id id_] *)
(*     | Entering ec -> *)
(*       E.encodeVariant "Entering" [entryCursor ec] *)
(*     | Dragging (tlid_, vp, hasMoved, wrappedCs) -> *)
(*       E.encodeVariant *)
(*         "Dragging" *)
(*         [tlid tlid_; vPos vp; E.bool hasMoved; cursorState wrappedCs] *)
(*     | SelectingCommand (tlid_, id_) -> *)
(*       E.encodeVariant "SelectingCommand" [tlid tlid_; id id_] *)
(*     | Deselected -> *)
(*       E.encodeVariant "Deselected" [] *)
(* end *)
