#!/usr/bin/env bash

set -euo pipefail

if [[ -S "/var/run/docker.sock" ]]; then
  sudo chmod 777 /var/run/docker.sock
else
  # We might not have the docker socket available on windows. Since we don't
  # need this all that much, let's just print a warning rather than expect
  # people to set this up.
  echo "No docker socket, skipping"
fi
