#!/usr/bin/env python3.6

# This is used, in concert with scripts/builder, to run Dark inside the dev
# container. There is a strong connection between these files and
# .circleci/config.yml. Generally, if you add something to one of these
# files, there's an equivalent to be added in .circleci/config.yml.

import subprocess
import sys
import threading
import time
import os
import signal

run_tests = False
freq = float(os.environ.get("POLL_FREQUENCY", "10"))


# Make io unbuffered
def flush(fn):
  def newfn(x):
    fn(x)
    sys.stdout.flush()

  return newfn


sys.stdout.write = flush(sys.stdout.write)
sys.stdout.writelines = flush(sys.stdout.writelines)


def run_or_fail(bash):
  if not run(bash):
    print("Failed during call: " + bash)
    sys.exit(-1)


def run(bash):
  proc = subprocess.run(bash, shell=True)
  return proc.returncode == 0


def compile(files):
  global run_tests
  if run_tests:
    test = "--test "
  else:
    test = ""
  fileStr = " ".join(files)
  try:
    return run(f"scripts/support/compile {test} {fileStr}")
  except:
    print(f"Tried to compile too many files. Length was {len(fileStr)}")
    return initial_compile()



def initial_backend_compile():
  files = [
      "backend/bin/server.ml",
      "backend/test/test.ml",
      "esy.json",
  ]
  return compile(files)


def initial_fsharp_backend_compile():
  files = [
      "fsharp-backend/global.json",
      "fsharp-backend/paket.lock",
      "fsharp-backend/src/LibExecution/LibExecution.fs",
  ]
  return compile(files)


def initial_client_compile():
  files = [
      "package.json",
      "client/src/Types.ml",
      "client/styles/app.scss",
      "client/test/ast_test.ml",
  ]
  return compile(files)


def initial_stroller_compile():
  files = ["containers/stroller/src/main.rs"]
  return compile(files)


def initial_scheduler_compile():
  files = [ "containers/queue-scheduler/src/main.rs" ]
  return compile(files)


def run_server():
  exit = compile(["scripts/support/runserver"])
  print("--------------------------")
  print("-- Started server ")
  print("--------------------------")
  return exit


# It is extremely challenging to get a non-blocking read on stdin.
# Essentially, we want to read everything from stdin and then compile.
# And if there isn't anything on stdin, sleep for a bit. The best way
# to do that is to read stdin in a separate thread, and every 300ms to
# check what has accumulated. Every other option I tried, including
# termios, epoll, either didn't work, or had a weird edge case. One
# nasty edge case is when you're saving all the time, as my editor is
# configured to do, it processes it one at a time and builds up a huge
# list of touched files, which it does one at a time, regardless of
# what's behind it in the queue.

inputBuffer = []
bufferLock = threading.Lock()


def process_watchers():
  global inputBuffer

  class InputThread(threading.Thread):
    def run(self):
      global inputBuffer
      while True:
        line = sys.stdin.readline()
        bufferLock.acquire()
        inputBuffer.insert(0, line)
        bufferLock.release()

  input_thread = InputThread()
  input_thread.daemon = True
  input_thread.start()

  while True:
    if len(inputBuffer) == 0:
      time.sleep(1 / freq)
    else:
      bufferLock.acquire()
      input = inputBuffer.copy()
      inputBuffer.clear()
      bufferLock.release()

      files = set()
      for line in input:
        for f in line.split("\n"):
          if f != "":
            try:
              f, _ = f.strip().split(" ")
              f = f.replace(os.environ["HOST_PWD"], "/home/dark/app")
              files.add(f)
            except:
              print("exception splitting: " + f)
      compile(files)


def background_task(fn, name):
  t = threading.Thread(target=fn)
  t.name = name
  t.start()


def main():
  # Recompile on file changes til infinity. This is our primary dev
  # mode. this is also used in scripts/builder.
  # See also run_tests (--test) which runs the tests too.
  watch = False

  # Compile it once - you usually want this to have full built code.
  # See also run_tests (--test) which runs the tests too.
  should_compile = False
  should_compile_client = False
  should_compile_backend = False
  should_compile_fsharp_backend = False
  should_compile_stroller = False
  should_compile_scheduler = False

  # Run the Dark webserver and keep the container open to serve it.
  # Useful for demoing without draining your battery. Will not recompile
  # like --watch does.
  should_serve = False

  for f in sys.argv[1:]:
    if f == "--compile":
      should_compile = True
      should_compile_backend = True
      should_compile_fsharp_backend = True
      should_compile_client = True
      should_compile_stroller = True
      should_compile_scheduler = True
    elif f == "--compile-backend":
      should_compile = True
      should_compile_backend = True
    elif f == "--compile-fsharp-backend":
      should_compile = True
      should_compile_fsharp_backend = True
    elif f == "--compile-client":
      should_compile = True
      should_compile_client = True
    elif f == "--compile-stroller":
      should_compile = True
      should_compile_stroller = True
    elif f == "--compile-scheduler":
      should_compile = True
      should_compile_scheduler = True
    elif f == "--watch":
      should_watch = True
    elif f == "--ci-serve":
      should_serve = True
    elif f == "--serve":
      should_serve = True
      should_compile = True
    elif f == "--test":
      global should_run_tests
      should_run_tests = True

  def initial_compile():
    success = True
    if should_compile_client and not initial_client_compile():
      print("Failed client build")
      success = False
    if should_compile_backend and not initial_backend_compile():
      print("Failed backend build")
      success = False
    if should_compile_fsharp_backend and not initial_fsharp_backend_compile():
      print("Failed backend build")
      success = False
    if should_compile_stroller and not initial_stroller_compile():
      print("Failed stroller build")
      success = False
    if should_compile_scheduler and not initial_scheduler_compile():
      print("Failed scheduler build")
      success = False

    print("--------------------------")
    if success:
      print("-- Initial compile succeeded")
    else:
      print("-- Initial compile failed")
    print("--------------------------")

    return success

  run_or_fail("scripts/support/write-config-file")
  run_or_fail("scripts/support/allow-docker-access")
  run_or_fail("scripts/support/create-app-directories")
  run_or_fail("scripts/support/create-cache-directories")
  run_or_fail("scripts/support/setup-hosts")
  run_or_fail("scripts/support/start-background-services postgresql")
  if should_compile:
    if should_watch or should_serve:
      background_task(initial_compile, "initial_compile")
    else:
      if initial_compile():
        sys.exit(0)
      else:
        sys.exit(1)
  else:
    if should_serve:
      #FSTODO
      run_server()

  if should_watch:
    import watchgod
    # watchgod scans the file system on a loop. This is extremely
    # fast so long as we list directory trees we don't want to go
    # into. We prefer this to notification based systems as we've
    # struggled to get them to work with our fun docker-based
    # setup.
    ignored=[".git",
             "_build",
             "_esy",
             "node_modules",
             "backend/static",
             "containers/stroller/target",
             "containers/queue-scheduler/target",
             "lib",
             "fsharp-backend/Build"]
    ignored = set(["/home/dark/app/" + f for f in ignored])
    for changes in watchgod.watch(
            "/home/dark/app/",
            watcher_cls=watchgod.AllWatcher,
            watcher_kwargs=dict(ignored_paths=ignored)):
      changes = [f for (_, f) in changes]
      compile(changes)

  elif should_serve:
    # pause to allow the server stay up
    signal.pause()


main()
