#!/usr/bin/env bash
. ./scripts/support/assert-in-container "$0" "$@"

set -euo pipefail

usage() {
    echo "usage: compile-project [name of project] [--test]
Compiles a dark project. Options are:
client, backend, fsharp-backend, stroller, queue-scheduler, all.
--test: runs tests
"
}

declare -A files
files["backend"]="backend/bin/server.ml backend/test/test.ml esy.json"
files["fsharp-backend"]="fsharp-backend/global.json fsharp-backend/paket.dependencies fsharp-backend/src/LibExecution/LibExecution.fs"
files["client"]="package.json client/src/Types.ml client/styles/app.scss client/test/ast_test.ml"
files["stroller"]="containers/stroller/src/main.rs"
files["queue-scheduler"]="containers/queue-scheduler/src/main.rs"
for v in "${files[@]}"; do
  files["all"]+=" $v"
done

while [ "$1" != "" ]; do
  case $1 in
    backend | client | stroller | queue-scheduler | all | fsharp-backend)
      ./scripts/support/compile ${files[$1]}
      exit
      ;;
    -h | --help )
      usage
      exit
      ;;
    * )
      usage
      exit 1
      ;;
  esac
  shift

done