#!/usr/bin/env bash

set -euo pipefail

NETWORK=dark-dev-net

EXISTING=$(docker network ls --filter name=$NETWORK -q)
if [[ $EXISTING == "" ]]; then
  echo "Creating docker network $NETWORK"
  docker network create $NETWORK
fi

