#!/usr/bin/env bash

set -euo pipefail

prepare () {
  sudo mkdir -p $1
  sudo chown dark:dark $1
}

prepare "/home/dark/.cargo"
prepare "/home/dark/.esy"
prepare "_build"
prepare "_esy"
prepare "lib"
prepare "node_modules"
prepare "containers/queue-scheduler/target"
prepare "containers/stroller/target"
