#!/usr/bin/env bash

set -euo pipefail

BINPATH="fsharp-backend/Build/out/"
# msbuild doesn't like to copy on top of a running server, so we have two files
# for each
API_SERVER_FILE="${BINPATH}/ApiServer.dll"
BWD_SERVER_FILE="${BINPATH}/BwdServer.dll"
API_SERVER_EXE="${BINPATH}/ApiServer2.dll"
BWD_SERVER_EXE="${BINPATH}/BwdServer2.dll"
#FSTODO
# QW_EXE="$BINPATH/QueueWorker"
# CRON_EXE="$BINPATH/CronChecker"
# TUNNEL_DAEMON_EXE="containers/tunnel/tunnel-daemon"

# Stop the server processes
echo "Stopping servers"
sudo pkill -f nginx || true
#FSTODO
sudo pkill -f "dotnet ${API_SERVER_FILE}" || true
sudo pkill -f "dotnet ${BWD_SERVER_FILE}" || true
sudo pkill -f "dotnet ${API_SERVER_EXE}" || true
sudo pkill -f "dotnet ${BWD_SERVER_EXE}" || true

#FSTODO
# pkill -f queue_worker.exe || true
# pkill -f cron_checker.exe || true

#FSTODO
# tunnel cleanup
# echo "pkill tunnel"
# sudo pkill -f "${TUNNEL_DAEMON_EXE}" || true
# echo "rm tunnel"
# sudo rm -rf /home/tunnel/.ssh/id_rsa{,.pub} /home/tunnel/.ssh/authorized_keys
# echo "pkill sleep"
# sudo pkill -f sleep.infinity || true
# end tunnel cleanup

echo "Waiting for postgres"
./scripts/support/wait-for-background-services postgresql

#FSTODO
# Run tunnel
# sudo mkdir -p /run/sshd
# echo "Starting tunnel"
# # shellcheck disable=SC2024
# sudo ./"${TUNNEL_DAEMON_EXE}" > rundir/logs/tunnel.log 2>&1 &
# echo "Started tunnel"

# if it hasn't been compiled yet, wait for it
echo "Waiting for compiled servers"
for ((i=1;i<=1000;i++));
do
  echo -n ""
  #FSTODO
  #if [[ ! -f "${SERVER_EXE}" || ! -f "${QW_EXE}" || ! -f "${CRON_EXE}" ]]; then
  # if [[ ! -f "${BWD_SERVER_EXE}" || ! -f "${API_SERVER_EXE}" ]]; then
  #   sleep 0.01
  # fi
done
echo "Done waiting for compiled servers"

#FSTODO
# symlink so nginx logs are visible on the host
# if [[ ! -f "/home/dark/app/rundir/logs/nginx-access.log" ]]; then
#   sudo rm /var/log/nginx/access.log
#   touch /home/dark/app/rundir/logs/nginx-access.log
#   ln -s /home/dark/app/rundir/logs/nginx-access.log /var/log/nginx/access.log
# fi

#FSTODO
# symlink so nginx logs are visible on the host
# if [[ ! -f "/home/dark/app/rundir/logs/nginx-error.log" ]]; then
#   sudo rm /var/log/nginx/error.log
#   touch /home/dark/app/rundir/logs/nginx-error.log
#   ln -s /home/dark/app/rundir/logs/nginx-error.log /var/log/nginx/error.log
# fi

#FSTODO
#if [[ -f "${SERVER_EXE}" && -f "${QW_EXE}" && -f "${CRON_EXE}" ]]; then

if [[ -f "${API_SERVER_FILE}" && -f "${BWD_SERVER_FILE}" ]]; then
  # msbuild won't compile onto files being run, so copy them first
  LOGS="${DARK_CONFIG_RUNDIR}/logs"
  cp "${API_SERVER_FILE}" "${API_SERVER_EXE}"
  cp "${BWD_SERVER_FILE}" "${BWD_SERVER_EXE}"
  cp "${BINPATH}/BwdServer.deps.json" "${BINPATH}/BwdServer2.deps.json"
  cp "${BINPATH}/BwdServer.runtimeconfig.dev.json" "${BINPATH}/BwdServer2.runtimeconfig.dev.json"
  cp "${BINPATH}/BwdServer.runtimeconfig.json" "${BINPATH}/BwdServer2.runtimeconfig.json"
  cp "${BINPATH}/BwdServer.xml" "${BINPATH}/BwdServer2.xml"
  echo "Running server"
  dotnet "${API_SERVER_EXE}" > "$LOGS/fsharp-apiserver.log" 2>&1 &
  dotnet "${BWD_SERVER_EXE}" > "$LOGS/fsharp-bwdserver.log" 2>&1 &
  #FSTODO
  # "${QW_EXE}" --no-health-check > "$LOGS/queue_worker.log" 2>&1 &
  # "${CRON_EXE}" --no-health-check > "$LOGS/cron.log" 2>&1 &

  #FSTODO
  # sudo rm -f /etc/nginx/nginx.conf
  # sudo rm -f /etc/nginx/conf.d/nginx.conf

  #FSTODO
  # sudo ln -s \
  #    /home/dark/app/containers/ocaml-nginx/base-nginx.conf \
  #    /etc/nginx/nginx.conf

  #FSTODO
  # sudo ln -s \
  #   /home/dark/app/containers/ocaml-nginx/nginx.conf \
  #   /etc/nginx/conf.d/nginx.conf

  #FSTODO
  # echo "Starting nginx"
  # sudo nginx &
  # echo "Started nginx"
else
  echo "Missing F# binaries (${BINPATH})"
  ls "${BINPATH}"
  exit 1
fi

echo "Finished loading server"