#!/usr/bin/env bash

set -euo pipefail

if [[ -v DARK_CONFIG_RUNNING_IN_GKE ]]; then
  sudo mkdir -p $DARK_CONFIG_RUN_DIR
fi

sudo chown dark $DARK_CONFIG_RUN_DIR

./scripts/support/write-config-file
./scripts/support/create-app-directories

echo "Starting server"
sudo --preserve-env ./bin/server.exe
