#!/usr/bin/env bash

set -euo pipefail

# generate an etags doc for the following files, put it in
# static/etags.json

cat > backend/static/etags.json <<EOF
{ "__date": "$(date -Iseconds)"
$(for file in $(find backend/static -type f -and -not -name "*.gz" -printf "%P\n"); do
  SHA="$(sha256sum backend/static/"$file" | cut -d " " -f 1)"
  echo ", \"${file/\"/\\\"}\": \"${SHA/\"/\\\"}\""
done)
}
EOF
