#!/bin/bash

set -euo pipefail

# generate an etags doc for the following files, put it in
# static/etags.json

cat > backend/static/etags.json <<EOF
{ "__date": "$(date -Iseconds)"
$(find backend/static -type f -printf "%P\n" > files_to_hash ;
while IFS= read -r file; do
  SHA="$(sha256sum backend/static/"$file" | cut -d " " -f 1)"
  echo ", \"${file/\"/\\\"}\": \"${SHA/\"/\\\"}\""
done < files_to_hash ;
rm files_to_hash)
}
EOF
