#!/usr/bin/env bash
set -x
echo $@
# this is run on the host when starting the vscode devcontainer. It makes sure
# the host is in the right shape so that the devcontainer can start up. This is
# cross-platform, and must run on windows, linux and Mac.

if [[ "${BASH_VERSINFO[0]}" -lt 4 ]]; then
  echo "We require bash >= 4, but this ran with bash ${BASH_VERSINFO[0]}"
  exit 1
fi

if [[ -v WSLENV ]]; then
  home=$(wslpath $1)
else
  home=$1
fi

echo "making ~/.dark_bash_history to share bash history with the Dark container"
touch "${home}/.dark_bash_history"

# We just need the directory to exist
mkdir -p "${home}/.config/gcloud"
