#!/bin/bash

set -euo pipefail

fswatch -m fsevents_monitor .browser-trigger |
    {
        while read event
        do
            echo "triggering reload"
            osascript scripts/support/chrome-reload.osa
        done
    }
