#! /usr/bin/env bash

# Note, *not* set -e, we explicitly want to loop if/when yarn install fails
# and don't want the script to fail. The set +e is unneccessary as it's the
# default, but putting it in to ensure nobody attempts to improve the script
# by adding set -e
set +e

SLEEP_SECONDS=3

for i in 1 2 3 4 5; do
  if [ $i -ne 1 ]; then
    echo "Yarn install failed; retrying"
  fi
  yarn install
  retval=$?

  if [[ $retval -eq 0 ]]; then
    # Sometimes yarn reports success but the node_modules folder is empty
    # This retries if the folder is empty
    if [ -z "$(ls -A node_modules)" ]; then
      echo "Yarn install reported success; but node_modules is empty!"
      retval=1 # override the erroneous zero retval
      sleep $SLEEP_SECONDS
    else
      break
    fi
  else
    sleep $SLEEP_SECONDS
  fi
done

# Preserve yarn's exit code
exit $retval

