#!/usr/bin/env bash

set -euo pipefail

sudo chown dark $DARK_CONFIG_RUN_DIR
sudo chown dark $DARK_CONFIG_PERSIST_DIR

./write-config-file
./create-app-directories
./start-background-services
./wait-for-background-services

echo "Starting server"
sudo --preserve-env ./bin/main.exe
