#!/usr/bin/env bash

set -euo pipefail

sudo service postgresql start
sudo service cron start

echo "Waiting for postgres"
until sudo service postgresql status; do
  printf '.'
  sleep 1
done

echo "Waiting for cron"
until sudo service cron status; do
  printf '.'
  sleep 1
done

echo "Starting server"
./main.exe
