#!/usr/bin/env bash

set -euo pipefail

if [[ -n $CI ]]; then
  TARGET=release
else
  TARGET=debug
fi

STROLLER="stroller/target/$TARGET/dark-stroller"

# Stop existing stroller (note that this makes the old process a zombie.
# Doesn't matter though, as this only runs in dev).
(ps aux | pgrep dark-stroller | xargs kill -9 > /dev/null 2>&1) || true

# if it hasn't been compiled yet, wait for it
for ((i=1;i<=1000;i++));
do
  if [[ ! -f "${STROLLER}" ]]; then
    sleep 0.01
  fi
done

if [[ -f "${STROLLER}" ]]; then
  LOGS="${DARK_CONFIG_RUNDIR}/logs"
  echo "Running stroller"
  "${STROLLER}" > "$LOGS/stroller.log" 2>&1 &
else
  echo "Missing binary"
  exit 1
fi
