#!/bin/bash

set -euo pipefail

NATIVE=1

BYTE_FILE="_build/bin/dark.byte"
NATIVE_FILE="_build/bin/dark.native"
if [ $NATIVE ]; then
  FILE=$NATIVE_FILE
else
  FILE=$BYTE_FILE
fi

# Stop the server
(ps aux | pgrep 'ocamlrun' | xargs kill -9 > /dev/null 2>&1) || true
(ps aux | pgrep $NATIVE_FILE | xargs kill -9 > /dev/null 2>&1) || true

# if it hasn't been compiled yet, wait for it
for ((i=1;i<=1000;i++));
do
  if [ ! -f "${FILE}" ]; then
    sleep 0.01
  fi
done

if [ -f "${FILE}" ]; then
    echo "Running server"
    if [ $NATIVE ]; then
      "${FILE}" > ../logs/server.log 2>&1 &
    else
      ocamlrun "${FILE}" > ../logs/server.log 2>&1 &
    fi
else
  echo "${FILE} doesn't exist"
  exit -1
fi
