#!/usr/bin/env bash

set -euo pipefail

#NATIVE=
NATIVE=1

BYTE_FILE="server/_build/default/bin/main.bc"
NATIVE_FILE="server/_build/default/bin/main.exe"
if [[ $NATIVE ]]; then
  FILE=$NATIVE_FILE
else
  FILE=$BYTE_FILE
fi


# Stop the server
(ps aux | pgrep 'ocamlrun' | xargs kill -9 > /dev/null 2>&1) || true
(ps aux | pgrep main.exe | xargs kill -9 > /dev/null 2>&1) || true

./scripts/support/wait-for-background-services

# if it hasn't been compiled yet, wait for it
for ((i=1;i<=1000;i++));
do
  if [[ ! -f "${FILE}" ]]; then
    sleep 0.01
  fi
done

if [[ -f "${FILE}" ]]; then
  LOGS="${DARK_CONFIG_RUN_DIR}/logs"
  echo "Running server"
  if [[ $NATIVE ]]; then
    "${FILE}" > "$LOGS/server.log" 2>&1 &
  else
    ocamlrun "${FILE}" > "$LOGS/server.log" 2>&1 &
  fi
else
  echo "${FILE} doesn't exist"
  exit -1
fi
