#!/usr/bin/env bash

set -euo pipefail

for name in "${@}"; do
  if [[ $name == postgresql ]]; then
    # for some reason, uncommenting the equivalent line in the Dockerfile doesn't do the
    # job. don't have time right now to figure out why.
    LA="listen_addresses = '*'"
    echo "$LA" | sudo tee -a /etc/postgresql/9.6/main/postgresql.conf

    # Fixed ownership and mode
    sudo chown systemd-network:crontab /etc/ssl/private/ssl-cert-snakeoil.key
    sudo chmod 0600 /etc/ssl/private/ssl-cert-snakeoil.key
    sudo chmod +rx /etc/ssl/private/
    sudo chown systemd-network:crontab -R /var/run/postgresql

  fi

  echo "--------------------------"
  echo "--  Starting $name"
  echo "--------------------------"
  sudo service "$name" start

done


