#!/usr/bin/env bash

set -euo pipefail

for name in ${@}; do
  if [[ $name == cron ]]; then
    TAB='*/1 * * * *'
    echo "$TAB $DARK_CONFIG_SCRIPTS_DIR/trigger_queue_workers >> $DARK_CONFIG_RUN_DIR/logs/cron.log 2>&1" | sudo crontab -
  fi

  echo "--------------------------"
  echo "--  Starting $name"
  echo "--------------------------"
  sudo service "$name" start
done


