#!/usr/bin/env bash
. ./scripts/support/assert-in-container "$0" "$@"

set -euo pipefail

# Stop ffmpeg recording
session=$(tmux list-sessions -F '#{session_name}' 2>/dev/null | grep "integrationTests-$1")
tmux send-keys -t "$session" q
