#!/bin/bash

set -euox pipefail

# kill all the children on exit
# (otherwise they hang around and keep the docker container running)
trap 'pkill -P $$' EXIT

cat > /etc/ssh/sshd_config <<EOF
ListenAddress localhost
PubkeyAuthentication yes
PasswordAuthentication no
AllowUsers tunnel
EOF

/usr/sbin/sshd

su tunnel <<EOF
# generate a new key
ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys

# pre-approve the fingerprint
ssh-keyscan -H localhost >> ~/.ssh/known_hosts
EOF

su tunnel -c "ssh -t -D *:1080 localhost sleep infinity" &

wait
