#!/usr/bin/env bash
. ./scripts/support/assert-in-container "$0" "$@"

set -euo pipefail

function check {
  if [[ "$1" == *"/services/"* ]]; then
    echo "kubeval $1"
    kubeval \
      --strict \
      --additional-schema-locations \
        https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master \
      --skip-kinds=ManagedCertificate,Issuer,CustomResourceDefinition \
      --kubernetes-version=1.19.9 \
      --force-color \
      "$1"
  else
    echo "not kubernetes so no kubeval: $1"
  fi
  # Too big to fuck with right now
  if [[ "$1" != *"/cert-manager.yaml" ]]; then
    echo "yamllint $1"
    yamllint "$1"
  fi
}

if [[ "$#" -eq 1 ]]; then
  check "$1"
else
  echo "checking yaml files ..."
  # skip circleci for now
  # shellcheck disable=SC2038
  FILES=$(find ./* -type f \
    \( -name "*.yml" \
    -o -name "*.yaml" \) -print \
    -o -path ".git" -prune \
    -o -path "_build" -prune \
    -o -path "./_build" -prune \
    -o -path "node_modules" -prune \
    -o -path "./node_modules" -prune \
    -o -path "_esy" -prune \
    -o -path "./_esy" -prune \
    -o -path "lib" -prune \
    -o -path "./lib" -prune \
    -o -path "esy.lock" -prune \
    -o -path "./esy.lock" -prune \
    -o -path "rundir" -prune \
    -o -path "./rundir" -prune \
    -o -path "containers/stroller/target" -prune \
    -o -path "./containers/stroller/target" -prune \
    -o -path "containers/queue-scheduler/target" -prune \
    -o -path "./containers/queue-scheduler/target" -prune \
    | grep -v circleci)
    for i in $FILES; do
      check $i
    done
  fi
