#!/usr/bin/env bash

set -euo pipefail

prepare () {
  sudo mkdir -p $1
  sudo chown -R dark:dark $1
}

prepare "_build"
prepare "_esy"
prepare "/home/dark/.esy"
prepare "node_modules"
prepare "lib"
prepare "fsharp-backend/Build"
