#!/usr/bin/env bash

set -euo pipefail

prepare () {
  sudo mkdir -p $1
  sudo chown -R dark:dark $1
}

prepare "backend/Build"
prepare "/home/dark/.nuget"
prepare "/home/dark/cloud-storage"
prepare "tree-sitter-darklang/build"
prepare "tree-sitter-darklang/node_modules"
