#!/bin/sh

# this is run on the host when starting the vscode devcontainer. It makes sure
# the host is in the right shape so that the devcontainer can start up. This is
# cross-platform, and must run on windows, linux and Mac. In particular, it
# must run in vscode's default docker container.

if [ -z "$WSLENV" ]; then
  home="$1"
else
  home=$(wslpath $1)
fi

# We just need the directory to exist
mkdir -p "${home}/.config/gcloud"
# Must exist and be a file
touch "${home}/.dark_bash_history"
