#!/usr/bin/env bash

set -euo pipefail

for name in "${@}"; do
  if [[ $name == postgresql ]]; then
    # for some reason, uncommenting the equivalent line in the Dockerfile doesn't do the
    # job. don't have time right now to figure out why.
    LA="listen_addresses = '*'"
    echo "$LA" | sudo tee -a /etc/postgresql/14/main/postgresql.conf
  fi

  echo "--------------------------"
  echo "--  Starting $name"
  echo "--------------------------"
  sudo service "$name" start

done


