#!/usr/bin/env bash

set -euo pipefail

echo "--------------------------"
echo "--  Starting yugabyte   --"
echo "--------------------------"

sudo chown -R dark:dark /home/dark/yugabyte-data

../yugabyte/bin/yugabyted start \
  --insecure \
  --base_dir /home/dark/yugabyte-data \
  --advertise_address 192.168.215.2