#!/usr/bin/env bash

set -euo pipefail

echo "--------------------------"
echo "--  Starting yugabyte   --"
echo "--------------------------"

sudo nohup ../yugabyte/bin/yugabyted start --insecure --base_dir /yugabyte-store > rundir/logs/yugabyte-startup &
