#!/usr/bin/env bash

set -euo pipefail

for name in "${@}"; do
  if [[ $name == postgresql ]]; then

    # When rebuilding the docker container (esp between ubuntu versions), the
    # postgres user may have a different userid, so fix up the existing volume
    sudo chown -R postgres:postgres /etc/postgresql
    sudo chown -R postgres:postgres /var/log/postgresql
    sudo chown -R postgres:postgres /var/lib/postgresql

    # for some reason, uncommenting the equivalent line in the Dockerfile doesn't do the
    # job. don't have time right now to figure out why.
    LA="listen_addresses = '*'"
    echo "$LA" | sudo tee -a /etc/postgresql/14/main/postgresql.conf

    # Fix weird permission problem, see from https://github.com/puntonim/docker-postgresql93/issues/2
    sudo chmod 766 /etc/ssl/private
    sudo chown postgres:postgres /etc/ssl/private/ssl-cert-snakeoil.key
    sudo mkdir /etc/ssl/private-copy
    sudo mv /etc/ssl/private/* /etc/ssl/private-copy/
    sudo rm -r /etc/ssl/private
    sudo mv /etc/ssl/private-copy /etc/ssl/private
    sudo chmod -R 0700 /etc/ssl/private
    sudo chown -R postgres /etc/ssl/private
  fi

  echo "--------------------------"
  echo "--  Starting $name"
  echo "--------------------------"
  sudo service "$name" start

done


