#!/usr/bin/env bash

set -euo pipefail

echo "--------------------------"
echo "--  Starting yugabyte   --"
echo "--------------------------"

sudo ../yugabyte/bin/yugabyted start --insecure --base_dir /yugabyte-store
