#!/usr/bin/env bash

set -euo pipefail


echo "Copying tree-sitter libraries (built in Dockerfile) to backend/src/LibTreeSitter"
TREE_SITTER_SOURCE="/home/dark/tree-sitter-builds/"
TREE_SITTER_TARGET="/home/dark/app/backend/src/LibTreeSitter/lib"

mkdir -p $TREE_SITTER_TARGET

if ls ${TREE_SITTER_SOURCE} 1> /dev/null 2>&1; then
  cp -r ${TREE_SITTER_SOURCE}* ${TREE_SITTER_TARGET}
else
  echo "Error: No tree-sitter libraries found in source directory."
  exit 1
fi


echo "Starting build server"

mkdir -p rundir/logs/

nohup ./scripts/build/_build-server --compile --watch &> /home/dark/app/rundir/logs/build-server.log &

# It seems that if we don't sleep here, the server does not start properly in all cases
sleep 2

echo "Build server started"
