#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

function wait_for {
  count=0
  until curl --output /dev/null --silent --show-error --fail "$1"; do
      ((count++)) && ((count==60)) && exit 1
      printf "waiting for %s\n" "$1"
      sleep 1
  done
}

wait_for http://${DARK_CONFIG_APISERVER_STATIC_HOST}/app.js
wait_for http://${DARK_CONFIG_APISERVER_STATIC_HOST}/app.css

# The static server is often ready before the ApiServer
wait_for http://${DARK_CONFIG_APISERVER_HOST}/check-apiserver