#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

base_url="$DARK_CONFIG_STATIC_HOST"

for cmd in "$@"; do
  case $cmd in
    --use-apiserver )
      base_url="$DARK_CONFIG_APISERVER_STATIC_HOST"
      ;;
    * )
      usage
      exit 1
      ;;
  esac
done

function wait_for {
  test_url="http://${base_url}/$1"
  count=0
  until curl --output /dev/null --silent --show-error --head --fail "${test_url}"; do
      ((count++)) && ((count==60)) && exit 1
      printf "waiting for %s at %s\n" "$1" "$test_url"
      sleep 1
  done
}

wait_for analysis.js
wait_for app.js
wait_for appsupport.js
wait_for app.css

