#!/usr/bin/env bash

set -eou pipefail

echo "Building docker image"

# See Dockerfile for an explanation of uid/gid.
gid="$(id -g)"
# Below is max($gid, 1000); on OS X, the user's group might be staff, with
# gid=20, which conflicts with ubuntu group dialout.
gid=$((gid > 1000 ? gid : 1000))
docker build -t dark --build-arg uid="$(id -u)" --build-arg gid="$gid" .

