#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

# Ensure that the etags file has the right entries. Used in CI.
check_presence () {
  name=$1
  echo "Checking $name"
  grep "$name" backend/static/etags.json

}

check_presence analysis.js
check_presence fetcher.js
check_presence appsupport.js
check_presence unsupportedBrowser.js
check_presence analysis.js
check_presence analysiswrapper.js
check_presence app.css
check_presence app.js
check_presence reset-normalize.css
check_presence BlazorWorker.js
check_presence blazor.webassembly.js

