#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

if [[ "$#" -eq 1 ]]; then
  echo "shellcheck $1"
  shellcheck -x -e SC2002 -e SC2044 -e SC2086 "$1"
else
  echo "shellcheck bash files ..."
  # In the scripts/ directory,
  # everything with a shebang containing sh (bash, sh)
  #
  # SC2044: https://github.com/koalaman/shellcheck/wiki/SC2044
  # SC2086: https://github.com/koalaman/shellcheck/wiki/SC2086
  # shellcheck disable=SC2038
  find ./* \
    -path ".git" -prune \
    -o -path "_build" -prune \
    -o -path "./_build" -prune \
    -o -path "node_modules" -prune \
    -o -path "./node_modules" -prune \
    -o -path "backend/static" \
    -o -path "./backend/static" \
    -o -path "client/static/vendor" \
    -o -path "./client/static/vendor" \
    -o -path "lib" \
    -o -path "./lib" \
    -o -path "integration-tests/node_modules" \
    -o -path "./integration-tests/node_modules" \
    -o -path "_esy" -prune \
    -o -path "./_esy" -prune \
    -o -path "lib" -prune \
    -o -path "./lib" -prune \
    -o -path "esy.lock" -prune \
    -o -path "./esy.lock" -prune \
    -o -path "rundir" -prune \
    -o -path "./rundir" -prune \
    -o -path "fsharp-backend/paket-files" -prune \
    -o -path "./fsharp-backend/paket-files" -prune \
    -o -path "fsharp-backend/Build" -prune \
    -o -path "./fsharp-backend/Build" -prune \
    -o -path "fsharp-backend/tests/staticassets-tests" \
    -o -path "./fsharp-backend/tests/staticassets-tests" \
    -o -type f \
    -exec awk 'FNR == 1 && /^#!.*sh/{print FILENAME}' {} + \
    | xargs shellcheck -e SC2002 -e SC2044 -e SC2086
fi





