#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

function check {
  if [[ "$1" == *"/services/"* && "$1" != *"/services/honeycomb-agent/config.yaml" && $(basename "$1") != "shipit.yaml" ]]; then
    echo "kubeconform $1"
    echo "$1" | check_k8s_files
  else
    echo "not kubernetes so no kubeconform: $1"
  fi
  # Too big to fuck with right now
  if [[ "$1" != *"/cert-manager.yaml" ]]; then
    echo "yamllint $1"
    yamllint "$1"
  fi
}

all_k8s_files() {
  find services/* \
    -path services/honeycomb-agent/config.yaml -prune \
    -o -name "shipit.yaml" -prune \
    -o -type f -name "*.yaml" -print
}

check_k8s_files() {
  xargs \
    kubeconform \
      -strict \
      -kubernetes-version 1.20.12 \
      -skip Certificate,ConfigConnector,StorageBucket,BackendConfig,CustomResourceDefinition,Issuer \
      -schema-location default \
      -schema-location 'scripts/linting/crd-schemas/{{ .ResourceKind }}{{ .KindSuffix }}.json'
}

all_yaml_files() {
  find ./* -type f \
    -path "./services/cert-manager/cert-manager.yaml" -prune \
    -o \( -name "*.yml" \
    -o -name "*.yaml" \) -print \
    -o -path ".git" -prune \
    -o -path "_build" -prune \
    -o -path "./_build" -prune \
    -o -path "node_modules" -prune \
    -o -path "./node_modules" -prune \
    -o -path "_esy" -prune \
    -o -path "./_esy" -prune \
    -o -path "lib" -prune \
    -o -path "./lib" -prune \
    -o -path "esy.lock" -prune \
    -o -path "./esy.lock" -prune \
    -o -path "rundir" -prune \
    -o -path "./rundir" -prune \
    -o -path "fsharp-backend/paket-files" -prune \
    -o -path "./fsharp-backend/paket-files" -prune \
    -o -path "containers/stroller/target" -prune \
    -o -path "./containers/stroller/target" -prune \
    -o -path "containers/queue-scheduler/target" -prune \
    -o -path "./containers/queue-scheduler/target" -prune \
    -o -path ".circleci/config.yml" -prune
}

if [[ "$#" -eq 1 ]]; then
  check "$1"
else
  echo "checking k8s files ..."
  all_k8s_files | check_k8s_files
  echo "linting yaml files ..."
  all_yaml_files | xargs yamllint
fi
