#!/usr/bin/env bash

set -euo pipefail

if [[ -v DARK_CONFIG_RUNNING_IN_GKE ]]; then
  sudo mkdir -p "$DARK_CONFIG_RUNDIR"
fi

sudo chown dark "$DARK_CONFIG_RUNDIR"

./scripts/devcontainer/_write-config-file
./scripts/devcontainer/_create-app-directories

echo "Starting cron checker"
sudo --preserve-env ./bin/cron_checker.exe
