#!/usr/bin/env bash
. ./scripts/support/assert-in-container $0 $@

set -euo pipefail

./translate/build

~/.local/bin/elm-format --json --elm-version 0.18 --stdin < /dev/stdin \
  | ./translate/_build/default/translate.exe --parse

