#!/usr/bin/env bash
. ./scripts/support/assert-in-container $0 $@

set -euo pipefail

srcdir=client
targetdir=client2/src

./translate/build

files=$(find ${srcdir} -name "*.elm" | grep -v elm-stuff | sort)

for src in $files; do
  # Snakecase it
  name=$(basename -- "$src")
  name=$(echo $name | sed -r 's/([A-Z])([A-Z]*)/\1\L\2/g') # group capital letters
  name=${name,} # lowercase first letter
  name=$(echo $name | sed -r 's/([A-Z])/_\L\1/g') # to snakecase
  name=${name%".elm"} # remove .elm suffix

  # Get the dir
  dir=$(dirname "$src")
  if [ "$dir" = "$srcdir" ]; then
    dir="";
  else
    dir="${dir#"${srcdir}/"}"
    dir="${dir}/"
  fi

  target="${targetdir}/${dir}${name}.ml"
  echo "${src} -> ${target}";
  newdir=$(dirname "${target}")
  mkdir -p "${newdir}"


  ~/.local/bin/elm-format --json --elm-version 0.18 --stdin < "${src}" \
    | ./translate/_build/default/translate.exe > "${target}" \
    && ocamlformat --inplace "${target}"

done



