#!/usr/bin/env bash
. ./scripts/support/assert-in-container $0 $@

set -euo pipefail

srcdir=client
targetdir=client2/src

./translate/build

files=$(find ${srcdir} -name "*.elm" | grep -v elm-stuff | sort)
ignore="DontPort.elm|Window/Events.elm|JSON.elm|DarkKeyboard.elm"
finished="Types.elm|Defaults.elm"
files=$(echo "$files" | egrep -v "$finished" | egrep -v "$ignore")

for src in $files; do
  # Snakecase it
  name=$(basename -- "$src")
  name=${name%".elm"} # remove .elm suffix

  # Get the dir
  dir=$(dirname "$src")
  if [ "$dir" = "$srcdir" ]; then
    dir="";
  else
    dir="${dir#"${srcdir}/"}"
    dir="${dir}/"
  fi

  target="${targetdir}/${dir}${name}.ml"
  echo "${src} -> ${target}";
  newdir=$(dirname "${target}")
  mkdir -p "${newdir}"


  ~/.local/bin/elm-format --json --elm-version 0.18 --stdin < "${src}" \
    | ./translate/_build/default/translate.exe > "${target}" \
    && ocamlformat --inplace "${target}"

done



