#!/usr/bin/env bash
. ./scripts/support/assert-in-container $0 $@

set -euo pipefail

./translate/build

~/.local/bin/elm-format --json --elm-version 0.18 --stdin < $1 \
  | ./translate/_build/default/translate.exe > out 2> stderr \
  && ocamlformat --inplace out

code=$?
cat out
cat stderr >&2
if [ code = 0 ]; then
  rm out
  rm stderr
fi

exit $code
