#!/usr/bin/env bash
. ./scripts/support/assert-in-container $0 $@

set -euo pipefail

./translate/build

~/.local/bin/elm-format --json --elm-version 0.18 --stdin < $1 \
  | ./translate/_build/default/translate.exe > out

ocamlformat --inplace out

cat out

rm out
