#!/usr/bin/env bash

set -euo pipefail

# cloud_sql_proxy notes:

# 1) `cloud_sql_proxy` is a google thing
# (https://cloud.google.com/sql/docs/postgres/sql-proxy) that takes your gcloud
# creds and uses them to open a proxy to the specified db.
#
# 2) -verbose=false because we don't need to know about non-error'ing client
# connection open/close events

PROJECT=balmy-ground-195100
REGION=us-west1
DB=dark-west
PORT=2346
INSTANCE="${PROJECT}:${REGION}:${DB}"

echo "Setting up proxy to production: ${INSTANCE} (port ${PORT})"

cloud_sql_proxy \
    -verbose=false \
    -instances "${INSTANCE}=tcp:${PORT}"
