#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

# we have a separate username and password for the chisel, HD server, and the ssh server
username=$(gcloud --project darklang-next secrets versions access latest --secret db-username)
password=$(gcloud --project darklang-next secrets versions access latest --secret db-password)

~/yugabyte/bin/ysqlsh "host=pub-us-central1.1c39714c-062a-40f3-b7ba-e320fce7ca3d.gcp.ybdb.io \
  user=$username \
  password=$password \
  dbname=yugabyte \
  sslmode=verify-full \
  sslrootcert=containers/yugabyte.crt"
