#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

# we have a separate username and password for the chisel, HD server, and the ssh server
username=$(gcloud secrets versions access latest --secret db-username)
password=$(gcloud secrets versions access latest --secret db-password)

~/yugabyte/bin/ysqlsh "host=pub-us-central1.ac92fd1c-c9e2-48b4-8a62-ec6809031dcc.gcp.ybdb.io \
  user=$username \
  password=$password \
  dbname=yugabyte \
  sslmode=verify-full \
  sslrootcert=containers/yugabyte.crt"
