#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

# Used for connection to a production container to run ExecHost commands

set -euo pipefail

./scripts/production/gcp-authorize-kubectl

kubectl exec --stdin --tty deploy/exechost-deployment -c exechost-ctr --namespace darklang -- /bin/bash
