#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

# we have a separate username and password for the chisel, HD server, and the ssh server
username=$(gcloud secrets versions access latest --secret prodexec-chisel-username)
password=$(gcloud secrets versions access latest --secret prodexec-chisel-password)
ssh_password=$(gcloud secrets versions access latest --secret prodexec-ssh-password)

# Google won't let us reach the server unless we are authenticated
header="Authorization: Bearer $(gcloud auth print-identity-token)"

sshpass -p "$ssh_password" \
  ssh \
  -o ProxyCommand="chisel client --auth '$username:$password' --header '$header' https://prodexec-d4mr6gl3ia-uc.a.run.app stdio:%h:%p" \
 "dark@localhost"