#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

# Connection to a production container

set -euo pipefail

./scripts/production/gcp-authorize-kubectl

kubectl exec --stdin --tty "$@" -- /bin/bash
