#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

# Used for connection to a production container to run ExecHost commands

set -euo pipefail

./scripts/production/gcp-authorize-kubectl

kubectl exec --stdin --tty gcp-exechost -- /bin/bash
