#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

# Copy secret from default namespace to darklang namespace

kubectl get secret $1 --namespace=default -o yaml \
  | sed 's/namespace: default/namespace: darklang/' \
  | kubectl apply --namespace=darklang -f -
