#!/usr/bin/env bash

. ./scripts/devcontainer/assert-in-container "$0" "$@"

set -euo pipefail

HELP="$(cat <<EOF
Usage: $0 username

Prints instructions for setting an emergency cookie to access darklang.com.

For use if auth0 or ops-login/login.darklang.com are down.
EOF
)"


username="${1:-}"
if [[ "${username}" = "" ]]; then
    echo "$HELP"
    exit 1
fi

./scripts/production/gcp-authorize-kubectl
pod="$(kubectl get pods \
    | grep "bwd.*Running" \
    | head -n 1 \
    | awk '{print $1}')"

exec kubectl exec -it ${pod} -c bwd-ctr bin/emergency_login_script.exe $username
