#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

# Set up connection
./scripts/production/gcp-authorize-kubectl
./scripts/production/_gcp-proxy-db & # Start early

PORT=2346

# Get credentials from production
SECRET=$(kubectl get secrets cloudsql-db-credentials -o json)

PGUSERNAME=$(echo "${SECRET}" |  jq -r '.data.username' | base64 -d)
PGPASSWORD=$(echo "${SECRET}" |  jq -r '.data.password' | base64 -d)
export PGUSERNAME
export PGPASSWORD

echo "Waiting for connection on port ${PORT}"
until pg_isready -h localhost -p "${PORT}" --user=${PGUSERNAME}
do
  sleep 0.3;
done

# Ensure we always have statement timeout set. This can be checked with `show
# statement_timeout;` and set to another value with something like `set
# statement_timeout=2s;`
PGOPTIONS="--statement-timeout=1s --lock-timeout=1s "
export PGOPTIONS

echo "Connecting to port ${PORT}"
psql -h localhost -p "${PORT}" --user=${PGUSERNAME} postgres "$@"
