#!/usr/bin/env bash
. ./scripts/devcontainer/assert-in-container "$0" "$@"

set -euo pipefail

PROJECT="balmy-ground-195100"
ZONE="us-west1"
CLUSTER="$(< current-cluster)"

gcloud container clusters get-credentials "--zone=${ZONE}" \
  "--project=${PROJECT}" "${CLUSTER}"
