#!/usr/bin/env bash

set -euo pipefail

if [[ -v DARK_CONFIG_RUNNING_IN_GKE ]]; then
  sudo mkdir -p "$DARK_CONFIG_RUNDIR"
fi

sudo chown dark "$DARK_CONFIG_RUNDIR"

./scripts/devcontainer/write-config-file
./scripts/devcontainer/create-app-directories

echo "Starting queue worker"
sudo --preserve-env ./bin/queue_worker.exe
