#!/usr/bin/env bash

set -euo pipefail

# This is used, in concert with scripts/support/build-server, to run Dark
# inside the dev container. There is a strong connection between these files
# and .circleci/config.yml. Generally, if you add something to one of these
# files, there's an equivalent to be added in .circleci/config.yml.

if [[ "${BASH_VERSINFO[0]}" -lt 4 ]]; then
  # Because we use `-v`
  echo "We require bash >= 4. Assuming you're on a Mac and have homebrew installed,"
  echo "upgrade by running \`brew install bash\`."
  exit 1
fi

if [ ! -v CI ]; then
  # Sometimes these dirs leak out of the container, causing confusion and
  # slowness
  rm -Rf _build
  rm -Rf _esy
  rm -Rf .esy
  rm -Rf node_modules
  rm -Rf lib
  rm -Rf stroller/target
  rm -Rf queue-scheduler/target
fi

# --------------
# Build image from clean start
# --------------
if [[ ! -v NEVER_REBUILD_DOCKER ]]; then
  echo "Building docker image"
  # See Dockerfile for an explanation of uid/gid.
  gid="$(id -g)"
  # Below is max($gid, 1000); on OS X, the user's group might be staff, with
  # gid=20, which conflicts with ubuntu group dialout.
  gid=$((gid > 1000 ? gid : 1000))
  docker build -t dark --build-arg uid="$(id -u)" --build-arg gid="$gid" .

  echo "Removing running containers"
  c=$(docker ps --filter "ancestor=dark" -q)
  if [[ -n "${c}" ]]; then
    docker kill "${c}";
  fi
fi

# --------------
# --------------
echo "watching for local changes"
RELOAD_BROWSER=""
for i in "$@"
do
  case $i in
      --watch)
	  RELOAD_BROWSER=true
    ;;
  esac
done

if [ -n "$RELOAD_BROWSER" ]; then
    echo "Starting the browser reload script"
    mkdir -p rundir/logs
    scripts/support/reload-browser > rundir/logs/browser.log 2>&1 &
fi

# --------------
# Mounts
# --------------

if [ -v CI ]; then
  # see "copy in data" in .circleci/config.yml
  MOUNTS="--volumes-from vols"
else
  MOUNTS="--mount type=bind,src=$PWD,dst=/home/dark/app"

  # Avoid docker syncing everything to the host, slowing compiles down by 5x
  MOUNTS+=" --mount type=volume,src=dark_build,dst=/home/dark/app/_build"
  MOUNTS+=" --mount type=volume,src=dark_esy,dst=/home/dark/app/_esy"
  MOUNTS+=" --mount type=volume,src=dark_dotesy,dst=/home/dark/.esy"
  MOUNTS+=" --mount type=volume,src=dark_node_modules,dst=/home/dark/app/node_modules"
  MOUNTS+=" --mount type=volume,src=dark_lib,dst=/home/dark/app/lib"
  MOUNTS+=" --mount type=volume,src=dark_stroller_target,dst=/home/dark/app/stroller/target"
  MOUNTS+=" --mount type=volume,src=dark_queue_scheduler_target,dst=/home/dark/app/queue-scheduler/target"
  MOUNTS+=" --mount type=volume,src=dark_rust_cargo,dst=/home/dark/.cargo"

  if [[ -e "$HOME/.config/gcloud" ]]; then
    MOUNTS="$MOUNTS --mount type=bind,src=$HOME/.config/gcloud,dst=/home/dark/.config/gcloud"
  fi
  # make sure this exists first, so it doesn't get created as a directory
  touch "$HOME/.dark_bash_history"
  MOUNTS="$MOUNTS --mount type=bind,src=$HOME/.dark_bash_history,dst=/home/dark/.bash_history"
fi

# --------------
# fswatch
# --------------
# Avoid hanging when --watch is not called. This runs the `true` command
# instead of fswatch.
FSWATCH="true"
for i in "$@"
do
  case $i in
    --watch)
    FSWATCH="fswatch --event-flag-separator=, -r * -x -e rundir"
    # Need to specify --event types, or something in node_modules will fire
    # endless IsDir and PlatformSpecific ("This event maps a platform-specific
    # event that has no corresponding flag.") events
    FSWATCH+=" --event=Created --event=Updated --event=Removed --event=Renamed --event=MovedFrom --event=MovedTo"

    # In case you are working on linux, it seems like poll_monitor is more reliable way
    # to check for the changes. You can find all monitors available on your platform
    # using `fswatch -M`. You can always override the monitor mode by passing
    # custom FSWATCH_MONITOR environment variable.
    if [[ "${FSWATCH_MONITOR-}" != "" ]]; then
      echo "Using fswatch with monitor from env: ${FSWATCH_MONITOR} (env)"
      FSWATCH+=" -m ${FSWATCH_MONITOR}"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
      echo "Using fswatch with monitor: poll_monitor (Linux default)"
      FSWATCH+=" -m poll_monitor"
    else
      echo "Using fswatch with monitor: (default)"
    fi
  esac
done

# --------------
# environment
# --------------

ENV="dev"
for i in "$@"
do
  case $i in
    --prodclone)
    ENV="dev_prodclone"
    ;;
  esac
done
if [ -v CI ]; then
  ENV="circleci"
fi

ENV_FILE="config/$ENV"

echo "Using env: $ENV_FILE"

# --------------
# save power with POLL_FREQUENCY
# --------------

POLL_FREQ=
if [ -v POLL_FREQUENCY ]; then
  POLL_FREQ="--env POLL_FREQUENCY=$POLL_FREQUENCY"
fi

# --------------
# create the network
# --------------
./scripts/support/create-dark-dev-network

# --------------
# --------------
echo "Run the build"

# --init here keeps orphaned processes (`<defunct>`, in ps) from
# hanging around forever; see https://tech.fpcomplete.com/rust/pid1
# (above the fold) for a description of the process 1 problem in
# docker, and
# https://docs.docker.com/engine/reference/run/#specify-an-init-process
# for documentation of --init.
# -p 5433:5432 to expose the postgres DB to outside the container
# -p 2345:2345 to expose the cloud_sql_proxy to outside the container
$FSWATCH | docker run \
             --init \
             --rm \
             -i \
             --dns 8.8.8.8 \
             --dns 8.8.4.4 \
             --name dark-dev \
             --hostname dark-dev \
             --env-file "$ENV_FILE" \
             --env HOST_PWD="$PWD" \
             --env IN_DEV_CONTAINER=true \
             --env CI="${CI-}" \
             --env CIRCLE_BRANCH="${CIRCLE_BRANCH-}" \
             --env CIRCLE_BUILD_URL="${CIRCLE_BUILD_URL-}" \
             $POLL_FREQ \
             -v pgconf:/etc/postgresql \
             -v pglogs:/var/log/postgresql \
             -v pgdata:/var/lib/postgresql \
             -v /var/run/docker.sock:/var/run/docker.sock \
             -p 8000:8000 \
             -p 5433:5432 \
             -p 2345:2345 \
             --security-opt seccomp=scripts/support/chrome-seccomp.json \
             -w /home/dark/app \
             $MOUNTS \
             dark \
             scripts/support/build-server "${@}"
