#!/usr/bin/env bash

set -euo pipefail

# Use to build image from clean start
if [[ ! -v NEVER_REBUILD_DOCKER ]]; then
  echo "Building docker image"
  docker build -t dark .

  echo "Removing running containers"
  c=$(docker ps -q)
  if [[ ! -z "${c}" ]]; then
    docker rm -f "${c}";
  fi
fi

echo "watching for local changes"
scripts/support/reload-browser > logs/browser.log 2>&1 &

if [ ! -v CI ]; then
  if [ ! -d ../conduit-frontend ]; then
    echo "pulling the conduit frontend"
    pushd .. && git clone git@github.com:darklang/conduit-frontend && popd
  fi
fi

# --------------
# Mounts
# --------------

# https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
if [ -v CI ]; then
  set -x
  # create some volumes to hold the dirs we would otherwise bind
  docker create \
    -v /home/dark/conduit-frontend \
    -v /home/dark/app  \
    --name vols \
    alpine:3.4 \
    /bin/true
  docker cp . vols:/home/dark/app
  # set the ownership of all this
  docker run -i --volumes-from vols dark \
    sudo chown -R dark /home/dark/app
  MOUNT="--volumes-from vols"
else
  MOUNT="--mount type=bind,src=$PWD,dst=/home/dark/app \
        --mount type=bind,src=$PWD/../conduit-frontend,dst=/home/dark/conduit-frontend"
fi

# --------------
# FSWatch
# --------------
# Avoid hanging when --watch is not called
FSWATCH="true"
for i in "$@"
do
  case $i in
    --watch)
    FSWATCH="fswatch --event-flag-separator=, -r * -x "
    ;;
  esac
done


# --------------
# Run the build
# --------------

echo "Run the build"
$FSWATCH | docker run \
             --rm \
             -i \
             $MOUNT \
             -v pgconf:/etc/postgresql \
             -v pglogs:/var/log/postgresql \
             -v pgdata:/var/lib/postgresql \
             -p 8000:8000 \
             -p 8001:8001 \
             --security-opt seccomp=scripts/support/chrome-seccomp.json \
             -w /home/dark/app \
             dark \
             scripts/support/build-server "${@}"

echo "exiting builder"
