#! /usr/bin/env bash
. ./scripts/support/assert-in-container "$0" "$@"

set -euo pipefail
set -x

DIR="$1"

if [[ "${DIR}" == "client" ]]; then
  scripts/ocamlformat-diff-all client
  # Include all prettifier files here, even if server
  client/node_modules/.bin/prettier -l \
     backend/templates/ui.html \
     integration-tests/tests.js \
     client/src/appsupport.js
  # TODO enable styles once things have settled down a bit over there
  #   client/src/styles/*
elif [[ "${DIR}" == "backend" ]]; then
  scripts/ocamlformat-diff-all backend
  # TODO sqlfmt for sql
  # TODO add python
else
  # TODO bash formatter
  echo "only supports client and backend"
  exit 1
fi

