#!/usr/bin/env bash

set -euo pipefail

docker volume rm \
  dark_build \
  dark_esy \
  dark_dotesy \
  dark_node_modules \
  dark_lib \
  dark_stroller_target \
  dark_queue_scheduler_target \
  dark_rust_cargo \
  dark_fsharp_build
