#!/usr/bin/env bash

set -euo pipefail

docker volume rm \
  dark_backend_build \
  dark_backend_esy \
  dark_backend_node_modules \
  dark_backend_dotesy \
  dark_client_node_modules \
  dark_client_lib \
  dark_stroller_target \
  dark_rust_cargo
