#!/usr/bin/env bash

set -euo pipefail

# It can be hard to recompile bucklescript-tea when you're editing a checkout
# of it. I'm not sure if this is true for all bs libraries, but if so this
# could probably be extended to handling them.

cd client \
  && rm -Rf node_modules/* node_modules/.* node_modules/.bin/ \
  && rm -Rf node_modules/bucklescript-tea/lib/ lib/* \
  && yarn install \
  && yarn run-s build:bsb build:js build:fetcher build:analysiswrapper
