#!/usr/bin/env bash
. ./scripts/support/assert-in-container "$0" "$@"

set -eou pipefail

HELP="$(cat <<EOF
Usage: $0

Compares the three different places that custom domains are stored to see if
anything has gone wrong.

The three places are:
- the custom_domains table in the DB
- the .spec.tls array in darkcustomdomain-l4-ingress
- the .spec.rules in darkcustomdomain-l4-ingress

For more docs, see docs/custom-domains.md
EOF
)"

if [[ $# -eq 1 && "$1" == '--help' ]]; then
    echo "$HELP"
    exit 1
fi

# This tmpfile crap is because for some reason gcp-psql hangs when put into a
# subshell ( foo=$(... | ./scripts/gcp-psql) ) or when its output is piped to
# another command (... | ./scripts/gcp-psql | grep ...)
tmpfile=$(mktemp /tmp/custom_domain.XXXXXX)
select_query="SELECT host FROM custom_domains"
echo "\\copy (${select_query}) TO ${tmpfile}" \
    | ./scripts/gcp-psql --production
DBHOSTS=$(cat ${tmpfile} | sort)

CERTMANAGER_JSON=$(kubectl get ingress darkcustomdomain-l4-ingress -o json)
TLSES=$(printf "%s" "${CERTMANAGER_JSON}" \
  | jq -r '.spec.tls | map ( .hosts[0] ) | sort | .[] ' \
  | grep -v ops-placeholder.darkcustomdomain.com)
RULES=$(printf "%s" "${CERTMANAGER_JSON}" \
  | jq -r '.spec.rules | map ( .host ) | sort | .[] ' \
  | grep -v ops-placeholder.darkcustomdomain.com)

if [[ "${TLSES}"x == "${DBHOSTS}"x && "${RULES}"x == "${DBHOSTS}"x ]]; then
  echo -e "\nAll entries match"
  echo "${DBHOSTS}"
  echo -e "\nAll entries match"
else
  echo -e "ERROR: Entries do not all match"
  echo -e "DB: \n${DBHOSTS}\n"
  echo -e "TLS: \n${TLSES}\n"
  echo -e "Rules: \n${RULES}\n"

  echo "DB hosts vs Rules:"
  diff <(echo "${DBHOSTS}") <(echo "${RULES}") || true
  echo -e "\nDB hosts vs TLSes:"
  diff <(echo "${DBHOSTS}") <(echo "${TLSES}") || true
  echo -e "\nTLSes vs Rules:"
  diff <(echo "${TLSES}") <(echo "${RULES}") || true

  echo -e "\nDB    sha: $(echo ${DBHOSTS} | sha1sum )"
  echo -e "TLS   sha: $(echo ${TLSES} | sha1sum )"
  echo -e "Rules sha: $(echo ${RULES} | sha1sum )\n"
  echo -e "ERROR: Entries do not all match"
  exit 1
fi
