#! /usr/bin/env bash
set -euo pipefail
set -x

# this script literally exists just to do the BRANCH check because I can't figure
# out circleci workflows + resource sharing and I've really had it up to _here_
# with circle.

if [[ "$CI" == "" ]]; then
  echo "Not on CI: Please follow workflow in the README for deploy"
else
  BRANCH=$(git rev-parse --abbrev-ref HEAD)
  if [[ "$BRANCH" == "master" ]]; then
    echo "--------------------------"
    echo "Fetching deploy key"
    echo "--------------------------"
    echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > gcloud-service-key.json
    docker cp gcloud-service-key.json dark-dev:/home/dark/app/gcloud-service-key.json

    ./scripts/run-in-docker gcloud auth activate-service-account \
      --key-file /home/dark/app/gcloud-service-key.json

    echo "--------------------------"
    echo "Pushing images"
    echo "--------------------------"
    ./scripts/run-in-docker scripts/gcp-push-images-to-gcr

    echo "--------------------------"
    echo "Pushing gzipped static assets"
    echo "--------------------------"
    # TODO ismith


    echo "--------------------------"
    echo "Pushing deploy to kubernetes"
    echo "--------------------------"
    ./scripts/run-in-docker scripts/gke-deploy
  else
    echo "Not on master, not deploying"
  fi
fi
