#!/bin/bash

set -euo pipefail

echo "Building docker image"
docker build -t dark .

echo "Removing all containers"
docker rm -f $(docker ps -a -q) || true

echo "watching for local changes"
scripts/browser_reload &

echo "Run the build"
docker run \
       -t \
       -v $(pwd):/home/dark/app \
       -p 8000:8000 \
       dark \
       sh -c 'cd app && scripts/build'
