#!/usr/bin/env bash
. ./scripts/support/assert-in-container "$0" "$@"

set -euo pipefail

NUMBER=$RANDOM
FILENAME="sqldump_$NUMBER.gz"
GSFILENAME=gs://download-gcp-db/$FILENAME
LOGFILE="sqldump_$NUMBER.log"
DB=prodclone
TEMPDB=prodcloneclone

###########################
echo "Exporting DB to $GSFILENAME "
###########################
ID=$(gcloud sql export sql dark-west $GSFILENAME --async --database=postgres)
gcloud beta sql operations wait --timeout=unlimited "${ID}"

###########################
echo "Downloading DB from $GSFILENAME"
###########################
gsutil cp $GSFILENAME .

###########################
echo "Dropping existing DB $DB (killing existing connections)"
###########################
dropdb --if-exists $TEMPDB
createdb $TEMPDB

###########################
echo "Loading DB $TEMPDB (logging to $LOGFILE)"
###########################
# There are some permission statements for cloudsql that are not relevant
gunzip --stdout $FILENAME | grep -v cloudsql | psql -d $TEMPDB > $LOGFILE

###########################
echo "Deleting dumpfiles ($GSFILENAME)"
###########################
gsutil rm $GSFILENAME

###########################
echo "Download complete. If this fails from here, restart your container and run ./scripts/reset-prodclone"
###########################

###########################
echo "Stopping procs, copying into $DB, restarting"
###########################
./scripts/reset-prodclone
rm $FILENAME

echo "Done. To reset prodclone again, run ./scripts/reset-prodclone"
