#!/usr/bin/env bash

# This script is specifically to trick vim's ALE elm mode to run in the
# container.

# ALE calls this with a tempdir, then uses it to check later, so get it
# right.
tempdir=
file=
while [[ $1 ]]; do
  if [[ $1 == *".elm"* ]]; then
    tempdir=$(dirname $1)
    file=$(basename $1)
  fi
  shift
done

# run it and get all the outputs
cd client && unbuffer elm-make --yes --warn --output=/dev/null --report=json $file | sed -e "s!$file!$tempdir/$file!g"
