#!/usr/bin/env bash
set -euo pipefail
./scripts/support/assert-in-container $0 $@

FORCE=""
for i in "$@"
do
  case $i in
    --force)
    FORCE="y"
    ;;
  esac
done

if [[ -e client/DEBUG ]]; then
  echo "client/DEBUG exists. Are you shipping a debug client?"
  exit 1
fi

PROJECT="balmy-ground-195100"
DNSZONE="--zone=dark-single-instance"
DNS_SETTINGS="--name=darksingleinstance.com. --type=A $DNSZONE"
FULL_DNS_SETTINGS="$DNS_SETTINGS --ttl=300"
INSTANCE="instance-4"
ZONE="us-west1-b"

GCLOUD="gcloud --project=$PROJECT "

CLOUDFLARE_ACCOUNT="paul.biggar@gmail.com"
CLOUDFLARE_ZONE="e2a8f090f530d9da76e54af6bdd097a2"
CLOUDFLARE_API_KEY="30d7a6ae4be97de5c052fcc33216396444d97"
CLOUDFLARE_PURGE_URL="https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE}/purge_cache"
ROLLBAR_ACCESS_TOKEN="ac042ea56b054bbdbddbfffaa149004e"
ENVIRONMENT=production
LOCAL_USERNAME=`cat ~/.config/gcloud/configurations/config_default | grep 'account' | awk '{print $3}' | awk -F "@" '{print $1}'`

#########################
# Deploy Docker image
#########################
IMAGE_ID=$(docker images dark-gcp -q | head -n 1)
IMAGE="gcr.io/$PROJECT/dark-prod:$IMAGE_ID"

echo "Deploying container to GCP"
docker tag dark-gcp:latest $IMAGE
$GCLOUD docker -- push $IMAGE

#########################
# Configure instance and containers
#########################

# Get the info from the running instance for use later
INFO=$($GCLOUD beta compute instances describe --zone=$ZONE $INSTANCE --format=json)
IP=$(echo $INFO | jq -r '.networkInterfaces[0].accessConfigs | map(select(.name == "External NAT"))[0].natIP | select (.!=null)')

if [ -z "$IP" ]; then
  echo "Couldn't parse instance IP from gcloud"
  exit 1
fi

# This updates automatically
echo "Setting GCP instance metadata"
$GCLOUD compute instances add-metadata --zone=$ZONE $INSTANCE \
  --metadata-from-file startup-script=scripts/support/gcp-instance-startup-script


# GCP always restarts, so only restart if something has changed
OLDIMAGE=$(echo $INFO | jq -r '.metadata.items | map(select(.key == "gce-container-declaration")) | .[0].value' | grep image | sed -E "s/[[:space:]]+image: //")

if [[ "$OLDIMAGE" != "$IMAGE" || "$FORCE" ]]; then
  echo "New image - updating container: $IMAGE"
  $GCLOUD beta compute instances update-container --zone=$ZONE $INSTANCE \
    --container-image $IMAGE \
    --container-env-file config/gcp-prod \
    --container-mount-host-path mount-path=/home/dark/gcp-persistdir,host-path=/mnt/disks/dark-disk/persistdir,mode=rw \
    --container-mount-host-path mount-path=/home/dark/gcp-rundir,host-path=/mnt/disks/dark-disk/rundir,mode=rw
  echo "Image $IMAGE deployed"

  echo "Waiting for deploy to be up"
  until $(curl --output /dev/null --silent --head --fail http://${IP}:80/static/elm.js); do
    echo -n '.'
    sleep 1
  done
  echo "Server is up"

  PURGE_OUTPUT=$(curl -s -X DELETE "${CLOUDFLARE_PURGE_URL}" -H "X-Auth-Email: ${CLOUDFLARE_ACCOUNT}" -H "X-Auth-Key: ${CLOUDFLARE_API_KEY}" -H "Content-Type: application/json" --data '{"purge_everything":true}' | jq ".success")

  if [[ "${PURGE_OUTPUT}" != "true" ]]; then
    PURGE_COMMENT="Failed to purge Cloudflare cache, try manual intervention: https://www.cloudflare.com/a/caching/darksingleinstance.com"
  else
    PURGE_COMMENT="Cloudflare cache purged"
  fi
  echo "${PURGE_COMMENT}"

  curl -s https://api.rollbar.com/api/1/deploy/ \
    -F access_token="${ROLLBAR_ACCESS_TOKEN}" \
    -F environment="$ENVIRONMENT" \
    -F revision="$IMAGE" \
    -F comment="${PURGE_COMMENT}" \
    -F local_username="${LOCAL_USERNAME}" > /dev/null

  echo "Rollbar notified."
else
  echo "Not updating container as image hasnt changed: $IMAGE (use --force to push anyway, eg if config/gcp-prod has changed)"
fi

#########################
# Set DNS
#########################

# We use a static DNS now, so commented this out. This was slightly
# buggy anyway, unsure why.

# OLDIP=$($GCLOUD dns record-sets list $DNS_SETTINGS \
#   --format=json | jq --raw-output .[0].rrdatas[0])
# NEWIP=$(echo $INFO \
#   | jq --raw-output .networkInterfaces[0].accessConfigs[0].natIP)


# echo "Setting DNS ($OLDIP -> $NEWIP)"
# if [[ -e transaction.yaml ]]; then
#   echo "Deleting old DNS"
#   $GCLOUD dns record-sets transaction abort $DNSZONE
# fi

# $GCLOUD dns record-sets transaction start $DNSZONE

# $GCLOUD dns record-sets transaction remove ${FULL_DNS_SETTINGS} $OLDIP
# $GCLOUD dns record-sets transaction add ${FULL_DNS_SETTINGS} $NEWIP

# $GCLOUD dns record-sets transaction execute $DNSZONE

rm -f transaction.yaml
