#!/usr/bin/env bash
. ./scripts/support/assert-in-container "$0" "$@"

set -euo pipefail
set -x

PREFIX=""
for i in "$@"
do
  case "${i}" in
    --prefix=*)
      PREFIX="${i/--prefix=/''}-"
      ;;
    *)
      echo "Unexpected argument: $i"
      exit 1
      ;;
  esac
done

PROJECT="balmy-ground-195100"

# get the latest local image ids
IMAGE_ID=$(docker images "${PREFIX}dark-gcp" -q | head -n 1)
QW_IMAGE_ID=$(docker images "${PREFIX}dark-gcp-qw" -q | head -n 1)
CRON_IMAGE_ID=$(docker images "${PREFIX}dark-gcp-cron" -q | head -n 1)
STROLLER_IMAGE_ID=$(docker images "${PREFIX}dark-gcp-stroller" -q | head -n 1)
TUNNEL_IMAGE_ID="$(docker images "${PREFIX}tunnel" -q | head -n 1)"
POSTGRES_HONEYTAIL_IMAGE_ID=$(docker images "${PREFIX}dark-gcp-postgres-honeytail" -q | head -n 1)

# get the image tag corresponding to the latest local image id
IMAGE="gcr.io/$PROJECT/${PREFIX}dark-gcp:$IMAGE_ID"
QW_IMAGE="gcr.io/$PROJECT/${PREFIX}dark-gcp-qw:$QW_IMAGE_ID"
CRON_IMAGE="gcr.io/$PROJECT/${PREFIX}dark-gcp-cron:$CRON_IMAGE_ID"
STROLLER_IMAGE="gcr.io/$PROJECT/${PREFIX}dark-gcp-stroller:$STROLLER_IMAGE_ID"
TUNNEL_IMAGE="gcr.io/$PROJECT/${PREFIX}tunnel:$TUNNEL_IMAGE_ID"
POSTGRES_HONEYTAIL_IMAGE="gcr.io/$PROJECT/${PREFIX}dark-gcp-postgres-honeytail:$POSTGRES_HONEYTAIL_IMAGE_ID"

# the tags we'll tag them with.
IMAGE_LATEST="gcr.io/$PROJECT/${PREFIX}dark-gcp:latest"
QW_IMAGE_LATEST="gcr.io/$PROJECT/${PREFIX}dark-gcp-qw:latest"
CRON_IMAGE_LATEST="gcr.io/$PROJECT/${PREFIX}dark-gcp-cron:latest"
STROLLER_IMAGE_LATEST="gcr.io/$PROJECT/${PREFIX}dark-gcp-stroller:latest"
TUNNEL_IMAGE_LATEST="gcr.io/$PROJECT/${PREFIX}tunnel:latest"
POSTGRES_HONEYTAIL_IMAGE_LATEST="gcr.io/$PROJECT/${PREFIX}dark-gcp-postgres-honeytail:latest"

#########################
# Deploy Docker image
#########################

echo "Deploying container to GCR"

# tag the most recent local containers with their ids.
docker tag "${PREFIX}dark-gcp:latest" "$IMAGE"
docker tag "${PREFIX}dark-gcp-qw:latest" "$QW_IMAGE"
docker tag "${PREFIX}dark-gcp-cron:latest" "$CRON_IMAGE"
docker tag "${PREFIX}dark-gcp-stroller:latest" "$STROLLER_IMAGE"
docker tag "${PREFIX}tunnel:latest" "$TUNNEL_IMAGE"
docker tag "${PREFIX}dark-gcp-postgres-honeytail:latest" "$POSTGRES_HONEYTAIL_IMAGE"

# tag the most recent local containers with :latest.
docker tag "${PREFIX}dark-gcp:latest" "$IMAGE_LATEST"
docker tag "${PREFIX}dark-gcp-qw:latest" "$QW_IMAGE_LATEST"
docker tag "${PREFIX}dark-gcp-cron:latest" "$CRON_IMAGE_LATEST"
docker tag "${PREFIX}dark-gcp-stroller:latest" "$STROLLER_IMAGE_LATEST"
docker tag "${PREFIX}tunnel:latest" "$TUNNEL_IMAGE_LATEST"
docker tag "${PREFIX}dark-gcp-postgres-honeytail:latest" "$POSTGRES_HONEYTAIL_IMAGE_LATEST"

# hook up gcloud docker
docker-credential-gcr configure-docker

# push the newly-tagged images
docker push "$IMAGE"
docker push "$IMAGE_LATEST"
docker push "$QW_IMAGE"
docker push "$QW_IMAGE_LATEST"
docker push "$CRON_IMAGE"
docker push "$CRON_IMAGE_LATEST"
docker push "$STROLLER_IMAGE"
docker push "$STROLLER_IMAGE_LATEST"
docker push "$TUNNEL_IMAGE"
docker push "$TUNNEL_IMAGE_LATEST"
docker push "$POSTGRES_HONEYTAIL_IMAGE"
docker push "$POSTGRES_HONEYTAIL_IMAGE_LATEST"
