#!/usr/bin/env bash
set -euo pipefail
./scripts/support/assert-in-container $0


DIR=$(mktemp -d --suffix _gcp-builddir)

cp scripts/support/gcp-Dockerfile $DIR/Dockerfile

cp -f scripts/support/gcp-run-server $DIR/
cp -Rf server/templates $DIR/
cp -Rf scripts $DIR/

mkdir -p $DIR/bin
cp -f server/_build/default/bin/*.exe $DIR/bin/

mkdir -p $DIR/webroot
cp -Rf server/static $DIR/webroot/

mkdir -p $DIR/swagger
cp -Rf server/swagger/*  $DIR/swagger/

mkdir -p $DIR/saved-apps
cp -Rf saved-apps/* $DIR/saved-apps/

docker build --build-arg GIT_COMMIT=$(git rev-parse --short HEAD) -t dark-gcp:latest $DIR


