#!/usr/bin/env bash
. ./scripts/support/assert-in-container "$0" "$@"

set -euo pipefail

./scripts/gcp-authorize-kubectl
PGPASSWORD=$(kubectl get secrets cloudsql-db-credentials -o json |  jq -r '.data.password' | base64 -d) \
  exec ./scripts/support/gcp-psql.exp
