#!/usr/bin/env bash
set -euo pipefail
. ./scripts/support/assert-in-container "$0" "$@"

c=$(docker ps --filter "ancestor=dark-gcp:latest" -q)
if [[ ! -z "${c}" ]]; then
  echo "Killing running containers"
  docker kill "${c}";
fi

case ${1:-server} in
  "queue") IMAGE="dark-gcp-qw";;
  "server") IMAGE="dark-gcp";;
  "cron") IMAGE="dark-gcp-cron";;
  *) IMAGE="dark-gcp";;
esac

./scripts/support/create-dark-dev-network

echo "Starting new container"
docker run \
  --rm \
  -it \
  --network dark-dev-net \
  --name $IMAGE-local \
  --env-file config/gcp-local \
  --mount type=bind,src=${HOST_PWD}/gcp-rundir,dst=/home/dark/gcp-rundir \
  $IMAGE:latest


