#!/usr/bin/env bash
set -euo pipefail
./scripts/support/assert-in-container $0 $@

FORCE=""
for i in "$@"
do
  case $i in
    --force)
    FORCE="y"
    ;;
  esac
done



PROJECT="balmy-ground-195100"
DNSZONE="--zone=dark-single-instance"
DNS_SETTINGS="--name=darksingleinstance.com. --type=A $DNSZONE"
FULL_DNS_SETTINGS="$DNS_SETTINGS --ttl=300"
INSTANCE="instance-4"
ZONE="us-west1-b"

GCLOUD="gcloud --project=$PROJECT "


#########################
# Deploy Docker image
#########################
IMAGE_ID=$(docker images dark-gcp -q | head -n 1)
IMAGE="gcr.io/$PROJECT/dark-prod:$IMAGE_ID"

echo "Deploying container to GCP"
docker tag dark-gcp:latest $IMAGE
$GCLOUD docker -- push $IMAGE

#########################
# Configure instance and containers
#########################

# Get the info from the running instance for use later
INFO=$($GCLOUD beta compute instances describe --zone=$ZONE $INSTANCE --format=json)

# This updates automatically
echo "Setting GCP instance metadata"
$GCLOUD compute instances add-metadata --zone=$ZONE $INSTANCE \
  --metadata-from-file startup-script=scripts/support/gcp-instance-startup-script


# GCP always restarts, so only restart if something has changed
OLDIMAGE=$(echo $INFO | jq -r '.metadata.items | map(select(.key == "gce-container-declaration")) | .[0].value' | grep image | sed -E "s/[[:space:]]+image: //")

if [[ "$OLDIMAGE" != "$IMAGE" || "$FORCE" ]]; then
  echo "New image - updating container: $IMAGE"
  $GCLOUD beta compute instances update-container --zone=$ZONE $INSTANCE \
    --container-image $IMAGE \
    --container-env-file config/gcp-prod \
    --container-mount-host-path mount-path=/home/dark/gcp-persistdir,host-path=/mnt/disks/dark-disk/persistdir,mode=rw \
    --container-mount-host-path mount-path=/home/dark/gcp-rundir,host-path=/mnt/disks/dark-disk/rundir,mode=rw
else
  echo "Not updating container as image hasnt changed: $IMAGE (use --force to push anyway, eg if config/gcp-prod has changed)"
fi

#########################
# Set DNS
#########################

# We use a static DNS now, so commented this out. This was slightly
# buggy anyway, unsure why.

# OLDIP=$($GCLOUD dns record-sets list $DNS_SETTINGS \
#   --format=json | jq --raw-output .[0].rrdatas[0])
# NEWIP=$(echo $INFO \
#   | jq --raw-output .networkInterfaces[0].accessConfigs[0].natIP)


# echo "Setting DNS ($OLDIP -> $NEWIP)"
# if [[ -e transaction.yaml ]]; then
#   echo "Deleting old DNS"
#   $GCLOUD dns record-sets transaction abort $DNSZONE
# fi

# $GCLOUD dns record-sets transaction start $DNSZONE

# $GCLOUD dns record-sets transaction remove ${FULL_DNS_SETTINGS} $OLDIP
# $GCLOUD dns record-sets transaction add ${FULL_DNS_SETTINGS} $NEWIP

# $GCLOUD dns record-sets transaction execute $DNSZONE

rm -f transaction.yaml
