#!/usr/bin/env bash
. ./scripts/support/assert-in-container $0 $@

set -euo pipefail

set -x

# Create the cluster
# gcloud beta container clusters create darkcluster1 \
#   --zone=us-west1 \
#   --project="balmy-ground-195100" \
#   --cluster-version=1.10.2-gke.3 \
#   --enable-stackdriver-kubernetes \
#   --enable-autorepair

# Get the creds to run kubectl
gcloud container clusters get-credentials projects/balmy-ground-195100/zones/us-west1/clusters/darkcluster1

# add secrets for the cloudsql proxy
kubectl create secret generic cloudsql-db-credentials --from-literal=username=postgres --from-literal=password=6gCtEAKElJFpNCdw

# add secrets for the cloudsql proxy service account
# Do this from outside the container cause it's not in the container
# kubectl create secret generic cloudsql-instance-credentials --from-file=credentials.json=/Users/paulbiggar/Downloads/balmy-ground-195100-cf744744111f.json


