#!/usr/bin/env bash
. ./scripts/support/assert-in-container "$0" "$@"

set -euo pipefail


# shellcheck disable=SC2010
MLFILES=$(ls backend/*/*.ml | grep -v test.ml)

LETS=$(grep -P -h '^let ' backend/*/*.ml{,i} \
        | sed 's/\s*let\s*//' \
        | awk '{print $1;}' \
        | sort \
        | uniq)

for z in $LETS; do
  echo -en "$z: " ;
  (grep "$z" "${MLFILES[@]}" || true ) | wc -l;
done | grep " 1$"
