#! /usr/bin/env bash
. ./scripts/support/assert-in-container $0 $@

find "${1}" \
  -path "backend/_build" -prune \
  -o -path "client/node_modules" -prune \
  -o -path "./client/node_modules" -prune \
  -o -path "./backend/_build" -prune \
  -o -name "*.ml" -print0 \
  -o -name "*.mli" -print0 \
  | xargs -0L1 ocamlformat --inplace

