#!/bin/bash

# A script to run ocamlformat within the container, same as we do for
# ocamlmerlin.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
"$DIR/run-in-docker" esy exec-command ocamlformat "${@}" <&0
