#!/usr/bin/env bash
. ./scripts/support/assert-in-container "$0" "$@"

set -euo pipefail


MLFILES=()
for mlfile in backend/*/*.ml; do
    if ! [[ "$mlfile" =~ test.ml ]]; then
        MLFILES+=( "$file" )
    fi
done

LETS=$(grep -P -h '^let ' backend/*/*.ml{,i} \
        | sed 's/\s*let\s*//' \
        | awk '{print $1;}' \
        | sort \
        | uniq)

for z in $LETS; do
  echo -en "$z: " ;
  (grep "$z" "${MLFILES[@]}" || true ) | wc -l;
done | grep " 1$"
