#!/bin/bash

# A script to run ocamlformat within the container, same as we do for
# ocamlmerlin.

script=$(basename "$0")

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
"$DIR/run-in-docker" "$script" "${@}" <&0
