#! /usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

TOKEN="${GITHUB_RELEASES_TOKEN}"
OWNER="darklang"
REPO="dark"
TAG="v0.0.1"
TARGET_COMMITISH="main"
NAME="cli-pre-release"
BODY="TODO: add a release description"

# Function to increment the tag number for a new release
increment_tag() {
  ## Fetch latest release tag
  latest_tag=$(curl -s "https://api.github.com/repos/$OWNER/$REPO/releases" | jq -r '.[0].tag_name')

  ## Check id latest tag is empty or null, if no tags found, start from v0.0.1
  if [ -z $latest_tag ] || [ $latest_tag = "null" ]; then
    echo "v0.0.1"
  else
    ## Major.Minor.Patch
    IFS='.' read -r -a version_numbers <<< "$latest_tag"
    major_number=${version_numbers[0]}
    minor_number=${version_numbers[1]}
    patch_number=${version_numbers[2]}
    patch_number=$((patch_number + 1))
    echo "${major_number}.${minor_number}.${patch_number}"
  fi
}

TAG=$(increment_tag)


# Create a GitHub release
response=$(curl -s -L \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $TOKEN" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/repos/$OWNER/$REPO/releases" \
  -d "{\"tag_name\":\"$TAG\",\"target_commitish\":\"$TARGET_COMMITISH\",\"name\":\"$NAME\",\"body\":\"$BODY\",\"draft\":false,\"prerelease\":true,\"generate_release_notes\":false}")

echo "Release creation response: $response"

## Check if release creation was successful
if [ "$(echo "$response" | jq -r '.id')" == "null" ]; then
  echo "Release creation failed"
  exit 1
fi


# Upload files to the release

## Extract the upload URL from the response: remove the {?name,label} part
upload_url=$(echo $response | jq -r .upload_url | sed -e "s/{?name,label}//")

## Upload all files in the clis directory
FILES_DIR="/Users/feriel/release/test-release/clis"

for FILE_PATH in "$FILES_DIR"/*; do
  if [[ -f "$FILE_PATH" ]]; then
    FILE_NAME=$(basename "$FILE_PATH")
    echo "Uploading file: $FILE_PATH"

    upload_response=$(curl -s -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $TOKEN" \
        -H "Content-Type: application/octet-stream" \
        "$upload_url?name=$FILE_NAME" \
        --data-binary @"$FILE_PATH")

    # Check if file upload was successful
    if [ "$(echo "$upload_response" | jq -r '.state')" != "uploaded" ]; then
      echo "Failed to upload file: $FILE_NAME"
      exit 1
    fi
  fi
done

echo "All files uploaded successfully"


# Delete old releases

## List all releases
list_releases_response=$(curl -s -L \
  -X GET \
  -H "Authorization: Bearer $TOKEN" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/$OWNER/$REPO/releases")

## Extract release IDs
release_ids=$(echo $list_releases_response | jq -r '.[].id')

## Extract the new release ID
new_release_id=$(echo $response | jq -r '.id')

## Loop through all release IDs and delete them, except the new release
for release_id in $release_ids; do
  if [ "$release_id" != "$new_release_id" ]; then
    echo "Deleting release: $release_id"
    curl -s -L \
      -X DELETE \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $TOKEN" \
      "https://api.github.com/repos/$OWNER/$REPO/releases/$release_id"
  fi
done

echo "Old releases deleted"
