#! /usr/bin/env bash
set -euo pipefail
set -x

PREFIX_TO_REMOVE="backend/static/"
rm -rf gzipped_assets; mkdir -p gzipped_assets

# We're not hashing the files in backend/static/vendor
# shellcheck disable=SC2044
for file in $(find backend/static -maxdepth 1 -type f -and -not -name etags.json -and -not -name "*.gz"); do
    basefile="$(basename "$file")"
    filehash="$(jq -r --arg FILE "${basefile}" '.[$FILE]' backend/static/etags.json)"
    hashed_file="${file%.*}-${filehash}.${basefile##*.}"

    # No .gz extension because gcloud cloud cdn doesn't want that
    gzip -c "${file}" > "gzipped_assets/${hashed_file//$PREFIX_TO_REMOVE}"
done

# We do want to compress the vendored files, though
# shellcheck disable=SC2044
for file in $(find backend/static -mindepth 2 -type f -and -not -name "*.gz"); do
    mkdir -p "gzipped_assets/$(dirname "${file//$PREFIX_TO_REMOVE}")"
    # No .gz extension because gcloud cloud cdn doesn't want that
    gzip -c "${file}" > "gzipped_assets/${file//$PREFIX_TO_REMOVE}"
done

(
  cd gzipped_assets
  # -m parallelizes upload
  # -n no-clobber - we don't need upload assets already there
  gsutil -m \
      -h 'Content-Encoding: gzip' \
      -h 'Cache-Control:public' \
      cp -a public-read -n -r . gs://darklang-static-assets
)

rm -r gzipped_assets
