#!/usr/bin/env bash
. ./scripts/support/assert-in-container $0 $@

set -euo pipefail

NUMBER=$RANDOM
FILENAME="sqldump_$NUMBER.gz"
GSFILENAME=gs://replace-pg-from-gcp/$FILENAME
LOGFILE="sqldump_$NUMBER.log"

###########################
echo "Exporting DB to $GSFILENAME "
###########################
gcloud sql export sql dark-west $GSFILENAME --database=postgres

###########################
echo "Downloading DB from $GSFILENAME"
###########################
gsutil cp $GSFILENAME .

###########################
echo "Loading DB (logging to $LOGFILE)"
###########################
dropdb postgres
createdb postgres

# There are some permission statements for cloudsql that are not relevant
gunzip --stdout $FILENAME | grep -v cloudsql | psql postgres > $LOGFILE

###########################
echo "Deleting dumpfiles ($GSFILENAME, $FILENAME)"
###########################
rm $FILENAME
gsutil rm $GSFILENAME


echo "Done"
