#!/usr/bin/env bash
. ./scripts/support/assert-in-container "$0" "$@"

set -euo pipefail

DB=prodclone
TEMPDB=prodcloneclone

###########################
echo "Stopping procs, copying into $DB, restarting"
###########################
killall psql || true
killall server.exe || true
killall queue_worker.exe || true
killall cron_checker.exe || true
dropdb $DB --if-exists
createdb -T $TEMPDB $DB
scripts/support/runserver


