#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

dropdb --if-exists testdb
createdb testdb
DARK_CONFIG_DB_HOST=localhost \
DARK_CONFIG_DB_DBNAME=testdb \
DARK_CONFIG_DB_USER=dark \
DARK_CONFIG_DB_PASSWORD=darklang \
"_build/default/backend/test/test.exe" "${@}"


