#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

PUBLISHED=false
CANVAS=

for i in "$@"
do
  case "${i}" in
    --published) PUBLISHED=true ;;
    *) CANVAS="${i}" ;;
  esac
done


if [[ "$PUBLISHED" == "true" ]]; then
  EXE="backend/Build/out/CanvasHack/Release/net7.0/linux-x64/CanvasHack"
else
  EXE="backend/Build/out/CanvasHack/Debug/net7.0/CanvasHack"
fi

./scripts/devcontainer/_wait-for-background-services postgresql

# if it hasn't been compiled yet, wait for it

for ((i=1;i<=1000;i++));
do
  if [[ ! -f "${EXE}" ]]; then
    echo "Waiting for compiled binary"
    sleep 0.01
  fi
done

set -x

echo "Clearing canvas before loading from disk"
./scripts/clear-canvas.sh "${CANVAS}"

echo "Running canvashack"
"${EXE}" "${CANVAS}"
