#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

# Part of F# tests. They block the dropdb call
sudo killall legacy_serializtion_server.exe || true
sudo killall legacy_fuzzing_server.exe || true
sudo killall ocamltestserver.exe || true
sudo killall server.exe || true
killall -9 Tests || true

dropdb --if-exists testdb
createdb testdb
DARK_CONFIG_DB_HOST=localhost \
DARK_CONFIG_DB_DBNAME=testdb \
DARK_CONFIG_DB_USER=dark \
DARK_CONFIG_DB_PASSWORD=darklang \
"_build/default/backend/test/test.exe" "${@}"


