#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail


BINPATH="_build/default/backend/bin"
SERVER_EXE="$BINPATH/server.exe"

# Stop the server processes
echo "Stopping servers"
sudo pkill -f nginx || true
sudo pkill -f server.exe || true
pkill -f queue_worker.exe || true
pkill -f cron_checker.exe || true

./scripts/run-httptunnel

# if it hasn't been compiled yet, wait for it
echo "Waiting for compiled servers"
for ((i=1;i<=1000;i++));
do
  if [[ ! -f "${SERVER_EXE}" ]]; then
    sleep 0.01
  fi
done
echo "Done waiting for compiled servers"

if [[ -f "${SERVER_EXE}" ]]; then
  LOGS="${DARK_CONFIG_RUNDIR}/logs"
  echo "Running server"
  # shellcheck disable=SC2024
  sudo --preserve-env "${SERVER_EXE}" > "$LOGS/server.log" 2>&1 &
  scripts/run-nginx-server
else
  echo "Missing OCaml binaries"
  exit 1
fi

echo "Finished loading server"
