#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

PUBLISHED=false

for i in "$@"
do
  case "${i}" in
    --published) shift; PUBLISHED=true ;;
  esac
done

if [[ "$PUBLISHED" == "true" ]]; then
  EXE="backend/Build/out/CLI/Release/net7.0/linux-x64/publish/CLI"
else
  EXE="backend/Build/out/CLI/Debug/net7.0/CLI"
fi

# if it hasn't been compiled yet, wait for it

for ((i=1;i<=1000;i++));
do
  if [[ ! -f "${EXE}" ]]; then
    echo "Waiting for compiled binary"
    sleep 0.01
  fi
done

"${EXE}" "$@"
