#!/usr/bin/env bash

set -euo pipefail

echo "Killing running containers"
c=$(docker ps --filter "ancestor=dark-gcp:latest" -q)
if [[ ! -z "${c}" ]]; then
  docker kill "${c}";
fi

echo "Starting new container"
docker run \
  --rm \
  -it \
  -p 9000:80 \
  --env-file config/local_gcp \
  -v gcp_pgconf:/etc/postgresql \
  -v gcp_pglogs:/var/log/postgresql \
  -v gcp_pgdata:/var/lib/postgresql \
  dark-gcp:latest


