#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

LOGS="${DARK_CONFIG_RUNDIR}/logs"
LOG="$LOGS/cloud-storage-emulator.log"

grey="\033[1;30m"
reset="\033[0m"

echo -e "Running Cloud Storage emulator ${grey}($LOG)${reset}"

killall fake-gcs-server || true
fake-gcs-server \
  -backend filesystem \
  -data /home/dark/cloud-storage/data \
  -filesystem-root /home/dark/cloud-storage/root \
  -port 4444 \
  -scheme http \
  -external-url http://localhost:4444 \
    > "$LOG" 2>&1 &

echo "Finished loading Cloud Storage emulator"