#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

# symlink so nginx logs are visible on the host
if [[ ! -f "/home/dark/app/rundir/logs/nginx-access.log" ]]; then
  sudo rm /var/log/nginx/access.log
  touch /home/dark/app/rundir/logs/nginx-access.log
  ln -s /home/dark/app/rundir/logs/nginx-access.log /var/log/nginx/access.log
fi

# symlink so nginx logs are visible on the host
if [[ ! -f "/home/dark/app/rundir/logs/nginx-error.log" ]]; then
  sudo rm /var/log/nginx/error.log
  touch /home/dark/app/rundir/logs/nginx-error.log
  ln -s /home/dark/app/rundir/logs/nginx-error.log /var/log/nginx/error.log
fi

sudo rm -f /etc/nginx/nginx.conf
sudo rm -f /etc/nginx/conf.d/nginx-apiserver.conf
sudo rm -f /etc/nginx/conf.d/nginx-bwdserver.conf

sudo ln -s \
  /home/dark/app/containers/ocaml-nginx/base-nginx.conf \
  /etc/nginx/nginx.conf

sudo ln -s \
  /home/dark/app/containers/ocaml-nginx/nginx.conf \
  /etc/nginx/conf.d/nginx-ocaml.conf

sudo ln -s \
  /home/dark/app/services/apiserver-deployment/nginx.conf \
  /etc/nginx/conf.d/nginx-apiserver.conf

sudo ln -s \
  /home/dark/app/services/bwdserver-deployment/nginx.conf \
  /etc/nginx/conf.d/nginx-bwdserver.conf

echo "Starting nginx"
sudo nginx &
echo "Started nginx"
