#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

trap ctrl_c INT

function ctrl_c() {
  killall -9 Build/out/FuzzTests
  exit 1
}

killall -9 FuzzTests || true

EXE=Build/out/FuzzTests/Debug/net6.0/linux-x64/FuzzTests

# Expecto has a number of async bugs causing it to hang. It appears to be due
# to the test framework though it's hard to tell. It's solved by disabling the
# spinner and not running the tests in parallel.
cd fsharp-backend
"${EXE}" --no-spinner --sequenced "${@}"
