#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

trap ctrl_c INT

function ctrl_c() {
  killall -9 Tests
  exit 1
}

killall -9 Tests || true

EXE=Build/out/DataTests/Debug/net7.0/linux-x64/DataTests

# No migrations

cd backend

DARK_CONFIG_TELEMETRY_EXPORTER=none \
"${EXE}" --no-spinner "${@}"
