#!/usr/bin/env bash

set -euo pipefail

function fix_dir_stdin {
  sed -e "s!$DIR!/home/dark/app!g"
}

function fix_dir_stdout {
  sed -e "s!/home/dark/app!$DIR!g" | sed -e "s!/home/dark/.opam/.*/bin!$DIR/scripts!g"
}

# Replace any filenames with the in-container filenames (stdin)
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
ARGS=${@}
ARGS=$(echo ${ARGS} | fix_dir_stdin)

if [[ -v CURRENTLY_REBUILDING_DOCKER ]];
then
  NAME=$(docker ps --last 2 --filter "ancestor=dark" --filter status=running --quiet | tail -n 1)
else
  NAME=$(docker ps --last 1 --filter "ancestor=dark" --filter status=running --quiet)
fi

if [ -t 0 ] ;
then
  docker exec -it ${NAME} bash -c "source /home/dark/.dark-config && ${ARGS}";
else
  # Replace any in-container filenames with host filesnames (stdout + stderr)
  { cat <&0 | fix_dir_stdin | docker exec -i ${NAME} bash -c "source /home/dark/.dark-config && ${ARGS}" 2>&1 1>&3 3>&- | fix_dir_stdout; } 3>&1 1>&2 | fix_dir_stdout
fi
