#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

PUBLISHED=false

for i in "$@"
do
  case "${i}" in
    --published)
    PUBLISHED=true
    shift
    ;;
  esac
done

if [[ "$PUBLISHED" == "true" ]]; then
  EXE="backend/Build/out/ExecHost/Release/net7.0/linux-x64/publish/ExecHost"
else
  EXE="backend/Build/out/ExecHost/Debug/net7.0/linux-x64/ExecHost"
fi

"${EXE}" "$@"
