#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

PUBLISHED=false

for i in "$@"
do
  case "${i}" in
    --published)
    PUBLISHED=true
    shift
    ;;
  esac
done

# Not used but they need to be running
./scripts/run-pubsub-emulator
./scripts/run-cloud-storage-emulator

if [[ "$PUBLISHED" == "true" ]]; then
  EXE="backend/Build/out/InternalCLI/Release/net7.0/linux-x64/publish/InternalCLI"
else
  EXE="backend/Build/out/InternalCLI/Debug/net7.0/InternalCLI"
fi

# if it hasn't been compiled yet, wait for it

for ((i=1;i<=1000;i++));
do
  if [[ ! -f "${EXE}" ]]; then
    echo "Waiting for compiled binary"
    sleep 0.01
  fi
done

"${EXE}" "$@"
