#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

TEST=false
PUBLISHED=false

grey="\033[1;30m"
reset="\033[0m"

for i in "$@"
do
  case "${i}" in
    --test)
    TEST=true
    shift
    ;;
    --published) PUBLISHED=true ;;
  esac
done

if [[ "$TEST" == "true" ]]; then
  LOG="${DARK_CONFIG_RUNDIR}/logs/test-packages.log"
else
  LOG="${DARK_CONFIG_RUNDIR}/logs/packages.log"
fi

# Not used but they need to be running
./scripts/run-pubsub-emulator
./scripts/run-cloud-storage-emulator

if [[ "$PUBLISHED" == "true" ]]; then
  EXE="backend/Build/out/LocalExec/Release/net7.0/linux-x64/publish/LocalExec"
else
  EXE="backend/Build/out/LocalExec/Debug/net7.0/LocalExec"
fi

echo -e "Loading packages ${grey}($LOG)${reset}"
"${EXE}" "$@" > $LOG 2>&1
