#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

PUBLISHED=false

for i in "$@"
do
  case "${i}" in
    --published)
      PUBLISHED=true
      ;;
    *) ARGS+=("${i}");;
  esac
done

# Not used but they need to be running
./scripts/run-pubsub-emulator
./scripts/run-cloud-storage-emulator

if [[ "$PUBLISHED" == "true" ]]; then
  EXE="backend/Build/out/LocalExec/Release/net7.0/linux-x64/LocalExec"
else
  EXE="backend/Build/out/LocalExec/Debug/net7.0/LocalExec"
fi

"${EXE}" "${ARGS[@]}"
