#!/bin/bash

#python server/main.py

ps aux | grep "main\.byte" | awk '{print $2}' | xargs kill

# if it hasn't been compiled yet, wait for it
for ((i=1;i<=100;i++));
do
  if [ ! -f "ocamlserver/main.byte" ]; then
    sleep 0.01
  fi
done


if [ -f "ocamlserver/main.byte" ]; then
    #COHTTP_DEBUG=true ocamlserver/main.byte > logs/server.log 2>&1 &
    OCAMLRUNPARAM=b ocamlserver/main.byte > logs/server.log 2>&1 &
else
  echo "ocamlserver/main.byte doesn't exist"
  exit -1
fi
