#!/usr/bin/env bash

set -euo pipefail

if [ ! -v CI ]; then
  cd "/home/dark/app"
  export DARK_LOGLEVEL="OFF"
  DATE="[$(date +'%Y-%m-%d %H:%M:%S')]"
  OUTPUT=$(/home/dark/app/server/_build/default/bin/trigger_queue_workers.exe)
  if [[ -z "${OUTPUT// }" ]]; then
    echo "$DATE No events to process"
  else
    echo "$DATE $OUTPUT"
  fi
fi
