#!/usr/bin/env bash
. ./scripts/support/assert-in-container $0 $@

set -euo pipefail

test_url="http://${DARK_CONFIG_STATIC_HOST}/darkjs.bc.js"
until $(curl --output /dev/null --silent --head --fail "${test_url}"); do
    printf 'j'
    sleep 1
done

test_url="http://${DARK_CONFIG_STATIC_HOST}/bsmain.js"
until $(curl --output /dev/null --silent --head --fail "${test_url}"); do
    printf 'e'
    sleep 1
done

test_url="http://${DARK_CONFIG_STATIC_HOST}/bsmain.js"
until $(curl --output /dev/null --silent --head --fail "${test_url}"); do
    printf 'b'
    sleep 1
done
