#!/usr/bin/env bash

set -euo pipefail

echo "Waiting for container to be running"
while [[ "$(docker ps --last 1 --filter status=running --quiet)" == "" ]]; do
  printf '.'
  sleep 1
done

echo "Waiting for postgres"
until scripts/run-in-docker service postgresql status; do
  printf '.'
  sleep 1
done


echo "Waiting for cron"
until scripts/run-in-docker service cron status; do
  printf '.'
  sleep 1
done

echo "Waiting for dnsmasq"
# Needs sudo
until scripts/run-in-docker sudo service dnsmasq status; do
  printf '.'
  sleep 1
done


