CREATE TABLE IF NOT EXISTS
accounts
( id UUID PRIMARY KEY
, username VARCHAR(255) UNIQUE NOT NULL
, name VARCHAR(255) NOT NULL
, email VARCHAR(255) NOT NULL
, admin BOOL NOT NULL DEFAULT FALSE
, password VARCHAR(255) NOT NULL
, created_at TIMESTAMP NOT NULL DEFAULT NOW()
, updated_at TIMESTAMP NOT NULL DEFAULT NOW())
