@startuml events-fsm
!include styles.puml

[*] -> new : emit
scheduled -> new : error (incr retries)
scheduled -> new : incomplete (do not incr retries)
new -> scheduled : scheduled for execution
scheduled -down-> error : error && retries > MAX
scheduled -> done : success
@enduml

@startuml events-seq
!include styles.puml

participant "cron checker" as cron
actor "end user" as user
participant "BWD handler" as handler
database events
participant "queue scheduler" as scheduler
participant "queue worker" as worker

alt event created by either cron or handler
  user -> handler : request
  handler -> events : emit
else
  cron -> events : enqueue
end

loop events may be scheduled multiple times (retry)
  events -> scheduler : find new events
  events <- scheduler : schedule events
  events -> worker : find scheduled events
  events <- worker : update success|failure
end
@enduml

