@startuml

!define COLOR_BLACK #111111
!define COLOR_GREY_LIGHT #EEEEEE
!define COLOR_GREY_MID #AAAAAA
!define COLOR_GREY_DARK #666666

!define COLOR_BLUE_LIGHT #C7D5EC
!define COLOR_BLUE_MID #566D94
!define COLOR_BLUE_DARK #142C54

!define COLOR_PURPLE_LIGHT #D0CAED
!define COLOR_PURPLE_MID #655999
!define COLOR_PURPLE_DARK #241858

!define COLOR_GREEN_LIGHT #C2EAE4
!define COLOR_GREEN_MID #498B82
!define COLOR_GREEN_DARK #0E5047

hide empty description
hide footbox

skinparam BackgroundColor transparent
skinparam DefaultFontColor COLOR_BLACK
skinparam DefaultFontSize 14
skinparam padding 5
skinparam roundcorner 10

skinparam Shadowing false

skinparam state {
  ArrowColor COLOR_GREY_DARK
  BackgroundColor COLOR_GREY_LIGHT
  BorderColor COLOR_GREY_DARK
}

skinparam note {
  BackgroundColor COLOR_GREY_LIGHT
  BorderColor COLOR_GREY_DARK
}

skinparam sequence {
  LifeLineBorderColor COLOR_GREY_MID
  BackgroundColor COLOR_GREY_LIGHT
  BorderColor COLOR_GREY_DARK
  GroupBorderColor COLOR_GREY_MID
}

skinparam participant {
  BackgroundColor COLOR_BLUE_LIGHT
  BorderColor COLOR_BLUE_DARK
}

skinparam actor {
  BackgroundColor COLOR_GREY_MID
  BorderColor COLOR_GREY_DARK
}

skinparam database {
  BackgroundColor COLOR_GREY_LIGHT
  BorderColor COLOR_GREY_DARK
}

@enduml
