#!/usr/bin/env bash

set -euo pipefail

sudo mkdir -p "$DARK_CONFIG_RUNDIR"
sudo chown dark "$DARK_CONFIG_RUNDIR"

./scripts/devcontainer/_write-config-file
./scripts/devcontainer/_create-app-directories

echo "Starting cronchecker"
./app/CronChecker
