#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

# Tell rollbar about a deploy

LOCAL_USERNAME="$(grep 'account' ~/.config/gcloud/configurations/config_default | awk '{print $3}' | awk -F "@" '{print $1}')"

ROLLBAR_ACCESS_TOKEN="ac042ea56b054bbdbddbfffaa149004e"
curl -s https://api.rollbar.com/api/1/deploy/ \
  -F "access_token=${ROLLBAR_ACCESS_TOKEN}" \
  -F "environment=production" \
  -F "revision=$(git rev-parse --short HEAD)" \
  -F "comment=$1" \
  -F "local_username=${LOCAL_USERNAME}" > /dev/null
echo "Rollbar notified."

