#!/usr/bin/env /bin/bash

set -euo pipefail
set -x

BUCKET="gs://darklang-downloads"


dir=`mktemp -d -t darklang-executor-XXXXXX`
file="$dir/darklang-executor-linux-x64"

cp backend/Build/out/Executor/Release/net6.0/linux-x64/publish/Executor "$file"
brotli -6 "$file" -o "$file.br"
ls -la $dir

gcloud storage cp \
  --verbosity debug \
  --content-type "application/octet-stream" \
  --cache-control "public, no-transform" \
  --content-encoding br \
  "$file.br" "$BUCKET"/darklang-executor-linux-x64

