#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

# List the deploy locks currently held

set -euo pipefail

DEPLOY_LOCK_BUCKET="gs://darklang-deploy-lock"

gcloud storage ls ${DEPLOY_LOCK_BUCKET}/ | sed 's!.*/!!'
