#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

# Clear all deploy locks

set -euo pipefail

curl -s https://ops-circleci.builtwithdark.com/deploy-lock \
  -X DELETE \
  -H 'Content-type: application/json' \
  -H "Authorization: Bearer ${DEPLOY_LOCK_TOKEN}" \
  | jq -r .
