#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

# Remove the deploy lock for this commit

set -euo pipefail

LOCKNAME=$(./scripts/deployment/deploy-lock-one-get-name)

./scripts/deployment/_deploy-lock-request "/${LOCKNAME}" DELETE | jq -r .