#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

# Remove the deploy lock for this commit

set -euo pipefail

LOCKNAME=$(./scripts/deployment/deploy-lock-one-get-name)

curl -s "https://ops-circleci.builtwithdark.com/deploy-lock/${LOCKNAME}" \
  -X DELETE \
  -H 'Content-type: application/json' \
  -H "Authorization: Bearer ${DEPLOY_LOCK_TOKEN}" \
  | jq  -r .