#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

# Clear all deploy locks

set -euo pipefail

DEPLOY_LOCK_BUCKET="gs://darklang-deploy-lock"

gsutil rm "${DEPLOY_LOCK_BUCKET}/*"
