#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

# Returns the name of the lock-file for this commit

COMMIT=$(git rev-parse --short HEAD)
TIMESTAMP=$(git show -s --format=%at HEAD)
LOCKFILE_ID="${TIMESTAMP}-${COMMIT}"

echo "deploy-lock-${LOCKFILE_ID}"
