#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

# Add a lock identifier for the commit and the timestamp.

set -euo pipefail

DEPLOY_LOCK_BUCKET="gs://darklang-deploy-lock"

LOCKFILE_NAME=$(./scripts/deployment/deploy-lock-one-get-name)
touch "$LOCKFILE_NAME"

echo "Adding lock file with id ${LOCKFILE_NAME}"

gsutil cp "${LOCKFILE_NAME}" "${DEPLOY_LOCK_BUCKET}"
rm "$LOCKFILE_NAME"
