#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

# Add a lock identifier for the commit and the timestamp.

set -euo pipefail

LOCKNAME=$(./scripts/deployment/deploy-lock-one-get-name)

echo "Adding lock file with name ${LOCKNAME}"

if [ ! -v DEPLOY_LOCK_TOKEN ] ;
then
  echo "No deploy lock token, get it from https://darklang.com/a/ops-circleci"
  exit 1
fi

curl -s https://ops-circleci.builtwithdark.com/deploy-lock \
  -X POST \
  -H 'Content-type: application/json' \
  -H "Authorization: Bearer ${DEPLOY_LOCK_TOKEN}" \
  -d "{ \"lockName\": \"${LOCKNAME}\" }" \
  | jq -r .
