#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

# Add a lock identifier for the commit and the timestamp.

set -euo pipefail

LOCKNAME=$(./scripts/deployment/deploy-lock-one-get-name)

echo "Adding lock file with name ${LOCKNAME}"

./scripts/deployment/_deploy-lock-request "/${LOCKNAME}" POST | jq -r .