#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

set -euo pipefail

# Deploy Dark to production

MANIFEST=""
MANUAL_DEPLOY="false"

HELP="$(cat <<EOF
Usage: $0 [OPTIONS]

Deployment script for CI

Options:
  --manifest=...    Manifest containing container shas
  --manual          Do a manual deploy
  --help            Display this menu.
EOF
)"

for i in "$@"
do
  case "${i}" in
    --manifest=*)
      MANIFEST="${i/--manifest=/''}"
      ;;
    --manual)
      MANUAL_DEPLOY="true"
      ;;
    --help)
      echo "$HELP"
      exit 0
      ;;
    *)
      echo "Unexpected argument: $i"
      echo "$HELP"
      exit 1
      ;;
  esac
done

if [[ "${MANUAL_DEPLOY}" == "true" ]]; then
  if [[ -v CI ]]; then
    echo "Manual deploy detected in CI"
    exit 1
  fi
else
  if [[ ! -v CI ]]; then
    echo "Automatic deploy detected outside CI"
    exit 1
  fi
fi

set -x

#############################
# set variables now so this fails early if they're not available
#############################

if [[ "${MANUAL_DEPLOY}" == "true" ]]; then
  CHANGE_CAUSE="manual deploy ; orig-time: $(date); git-commit: $(git rev-parse --short HEAD)"
else
  CHANGE_CAUSE="circle=${CIRCLE_BUILD_URL} ; orig-time: $(date); git-commit: $(git rev-parse --short HEAD)"
fi

#############################
# Ensure we got a good one
#############################
./scripts/deployment/shipit validate

#############################
# Lock before doing a deploy (unlocks on fail or at end of file)
#############################

if [[ "${MANUAL_DEPLOY}" == "true" ]]; then
  LOCKFILE_ID="manual-deploy"
else
  LOCKFILE_ID="${CIRCLE_BUILD_NUM}"
fi

cleanup_deploy_lock() {
  trap '' EXIT # some shells will call EXIT after the INT handler
  echo "Removing deploy lock"
  ./scripts/deployment/deploy-lock-remove "${LOCKFILE_ID}"
  exit 1
}

# Make sure we remove the lockfile if this script exits early for some reason
trap cleanup_deploy_lock INT QUIT TERM ERR

# We source this instead of running it in a subshell so that the trap works as expected
./scripts/deployment/deploy-lock-acquire "${LOCKFILE_ID}"

#############################
# Check it's safe to deploy
#############################

# Check that the prod cluster matches our view of the world, once we have the lock
./scripts/deployment/shipit manual diff > /dev/null 2>&1

# Check that the everything can be deployed
./scripts/deployment/shipit release push --dry-run=client --arg CHANGE_CAUSE="${CHANGE_CAUSE}" --manifest="$MANIFEST"
./scripts/deployment/shipit release push --dry-run=server --arg CHANGE_CAUSE="${CHANGE_CAUSE}" --manifest="$MANIFEST"

#############################
# Actually do the deploy
#############################

# Old stuff
kubectl create configmap base-nginx --from-file=containers/ocaml-nginx/base-nginx.conf -o yaml --dry-run=client | kubectl replace -f -
kubectl create configmap nginx --from-file=containers/ocaml-nginx/nginx.conf -o yaml --dry-run=client | kubectl replace -f -
# CLEANUP: we can remove the `nginx` configmap once the users are long gone

# deploy the config for the newly-created deployment containers
./scripts/deployment/shipit release push --arg CHANGE_CAUSE="${CHANGE_CAUSE}" --manifest="$MANIFEST"

#########################
# Tell everyone about the deploy
#########################

./scripts/deployment/_notify-deployment-rollbar
./scripts/deployment/_notify-deployment-honeycomb

####################
# Unlock post-deploy
####################
./scripts/deployment/deploy-lock-clear
