#!/usr/bin/env bash
. ./scripts/devcontainer/_assert-in-container "$0" "$@"

# Do a dry run of all kubernetes files

set -euo pipefail

function check {
  if [[ "$1" == *config* ]]; then
    echo "checking $1"
    kubectl apply -f "$1" --dry-run=client
  fi
}

if [[ "$#" -eq 1 ]]; then
  check "$1"
else
  echo "checking yaml files ..."
  # skip circleci for now
  # shellcheck disable=SC2038
  FILES=$(find ./services/* -type f \
    \( -name "*.yml" \
    -o -name "*.yaml" \) \
    ! -path "./services/honeycomb-agent/honeycomb-agent-config.yaml" \
    ! -path "./services/configconnector/config-connector-experiment-ingress.yaml" \
    -print )
    for i in $FILES; do
      check $i
    done
  fi
